#!/usr/bin/env python3
"""The paper's macros (results/macros.tex) from analysis/analyse.py's summary.json only.

    macros.py SUMMARY_JSON [--out results/macros.tex]

Every number the paper states comes from here (CLAUDE.md: "Numbers in papers come only from
generated results/macros.tex"; hypotheses.md section 13), and every macro here comes from
summary.json: nothing is typed in by hand. Names are letters only, never a digit: each part of a
cell id maps to a word (C1 is COne, io_uring is Iouring, caddy-l4 is CaddyLFour), and a name that
would hold anything else stops the run. A macro whose value is missing from the summary (a cell
without its sessions) is not written, so LaTeX stops on it rather than print a stale value.

Adapted from the previous paper's analysis/macros.py and macros_util.py (papers/typed-routing,
same author): the macro store, the rounding rule (half away from zero on the shortest decimal
form), thousands grouped by a thin comma. A synthetic summary gets a warning in its first line and
is never written under results/.
"""

from __future__ import annotations

import argparse
import json
import math
import re
import sys
from decimal import ROUND_HALF_UP, Decimal
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

import versions  # noqa: E402

HEAD = "% Generated by analysis/macros.py from analysis/analyse.py's summary.json. Do not edit.\n"
SYNTHETIC_HEAD = "% SYNTHETIC DATA from analysis/synth.py, for the tests. Never under results/, never cited.\n"

WORDS = {
    "C1": "COne", "C2": "CTwo", "C3": "CThree", "B3": "BThree", "M1": "MOne", "M2": "MTwo", "M3": "MThree", "S": "Sec",
    "L": "L", "W": "W", "epoll": "Epoll", "io_uring": "Iouring", "IOCP": "Iocp",
    "http1": "Http", "h2c": "HTwoC", "tls": "Tls", "mqtt": "Mqtt", "ssh": "Ssh", "tls-stub": "TlsSni",
    "nginx": "Nginx", "haproxy": "Haproxy", "envoy": "Envoy", "caddy-l4": "CaddyLFour", "sslh-ev": "SslhEv",
    "netty": "Netty", "jetty": "Jetty", "cmux": "Cmux", "hyper-util": "HyperUtil",
    "silent": "Silent", "partial-hello": "PartialHello",
    "mixed": "Mixed", "tls-variants": "TlsVariants", "resumption": "Resumption", "alpn-h2": "AlpnHTwo",
    "two-cores": "TwoCores", "reuseport": "Reuseport", "relay-io_uring": "RelayIouring", "iocp-forms": "IocpForms",
    "acceptex-buffer": "AcceptexBuffer", "receive-form": "ReceiveForm", "m-ttfb": "MTtfb", "b3-other-mode": "BThreeOtherMode",
    "cpu": "Cpu", "rss": "Rss", "rss_peak": "RssPeak", "ttfb_p99": "TtfbPNinetyNine", "value": "Value",
    "wl4": "WLFour", "m-ttfb-cpu": "MTtfbCpu", "by-job": "ByJob",
}
PROTO_TEXT = {"http1": "HTTP/1.1", "h2c": "h2c", "tls": "TLS", "mqtt": "MQTT"}


# ---------------------------------------------------------------- formatting


def fixed(x: float, places: int) -> str:
    q = Decimal(repr(float(x))).quantize(Decimal(1).scaleb(-places), rounding=ROUND_HALF_UP)
    return grouped(f"{q:f}")


def grouped(s: str) -> str:
    sign, s = ("-", s[1:]) if s.startswith("-") else ("", s)
    whole, _, frac = s.partition(".")
    if len(whole) > 3:
        parts = []
        while len(whole) > 3:
            parts.insert(0, whole[-3:])
            whole = whole[:-3]
        whole = "{,}".join([whole] + parts)
    return sign + whole + ("." + frac if frac else "")


def ratio(x: float) -> str:
    """Ratios and their interval bounds: four decimals."""
    return fixed(x, 4)


def bytes_(x: float) -> str:
    """Bytes per pending connection: one decimal."""
    return fixed(x, 1)


def power(x: float) -> str:
    return fixed(x, 3)


def count(n) -> str:
    return grouped(str(int(n)))


def scientific(x: float) -> str:
    """p-values, math mode: a.b x 10^e."""
    if x == 0:
        return "0"
    e = math.floor(math.log10(abs(x)))
    m = Decimal(repr(x / 10 ** e)).quantize(Decimal("0.1"), rounding=ROUND_HALF_UP)
    if m >= 10:
        m, e = m / 10, e + 1
    return f"{m}\\times10^{{{e}}}"


# ---------------------------------------------------------------- the store


class Macros:
    def __init__(self) -> None:
        self.items: list[tuple[str, str, str]] = []
        self.names: set[str] = set()

    def add(self, name: str, value, note: str = "") -> None:
        if value is None:
            return
        if not re.fullmatch(r"[A-Za-z]+", name):
            raise ValueError(f"macro name {name!r} is not letters only")
        if name in self.names:
            raise ValueError(f"macro {name} defined twice")
        self.names.add(name)
        self.items.append((name, str(value), note))

    def text(self) -> str:
        return "".join(f"\\newcommand{{\\{n}}}{{{v}}}" + (f"  % {note}" if note else "") + "\n" for n, v, note in self.items)


def word(cell_id: str) -> str:
    """C1.L.epoll.http1 -> COneLEpollHttp; every part must have a word."""
    out = []
    for part in cell_id.split("."):
        if part not in WORDS:
            raise ValueError(f"no macro word for {part!r} of {cell_id}")
        out.append(WORDS[part])
    return "".join(out)


def opt(f, x):
    return None if x is None else f(x)


# ---------------------------------------------------------------- sections


def design(mc: Macros, s: dict) -> None:
    k = s["constants"]
    mc.add("Alpha", fixed(k["alpha"], 3), "family-wise, one-sided (Words)")
    mc.add("Resamples", count(k["resamples"]), "BCa resamples (4.2)")
    mc.add("CostMarginLow", fixed(k["cost_margin"][0], 2))
    mc.add("CostMarginHigh", fixed(k["cost_margin"][1], 2))
    mc.add("BThreeBound", fixed(k["b3_bound"], 2))
    mc.add("CostR", count(k["R_C"]), "R_C from the pilot entry")
    mc.add("BThreeR", count(k["R_B"]))
    mc.add("MR", count(k["R_M"]))
    for name, v in sorted(s["seeds"].items()):
        mc.add("Seed" + "".join(p.capitalize() for p in name.split("_")[1:]), count(v))
    mc.add("CostM", count(s["pilot"]["m_C"]), "m_C, the resolved cells")


def family(mc: Macros, s: dict, fam: str, prefix: str) -> None:
    f = s["families"][fam]
    mc.add(f"{prefix}Holm", count(f["m"]), "cells in Holm")
    mc.add(f"{prefix}Passed", count(f["passed"]), "pass under both computations")
    mc.add(f"{prefix}PassedBoot", count(f["passed_boot"]))
    mc.add(f"{prefix}PassedSign", count(f["passed_sign"]))
    mc.add(f"{prefix}Disagree", count(f["disagree"]))
    for x in f["cells"]:
        w = word(x["cell"])
        ci = x.get("ci95") or [None, None]
        ch = x.get("ci_holm") or [None, None]
        mc.add(f"{w}Valid", count(x["valid_sessions"]))
        mc.add(f"{w}Median", opt(ratio, x.get("median")))
        mc.add(f"{w}Low", opt(ratio, ci[0]))
        mc.add(f"{w}High", opt(ratio, ci[1]))
        mc.add(f"{w}HolmLow", opt(ratio, ch[0]))
        mc.add(f"{w}HolmHigh", opt(ratio, ch[1]))
        if x["tested"]:
            mc.add(f"{w}PBoot", scientific(x["p_boot"]))
            mc.add(f"{w}PSign", scientific(x["p_sign"]))
            if "sign_x" in x:
                mc.add(f"{w}SignX", count(x["sign_x"]))
            else:
                mc.add(f"{w}SignXLow", count(x["sign_x_low"]))
                mc.add(f"{w}SignXHigh", count(x["sign_x_high"]))
        if x["holm"]:
            mc.add(f"{w}Holds", "holds" if x.get("passes") else "does not hold")
        mc.add(f"{w}Verdict", x["verdict"].replace("<=", "$\\le$"))
        mc.add(f"{w}InvalidWindows", count(sum(len(v) for v in x["invalid_windows"].values())))
        if "D" in x:
            mc.add(f"{w}DMedian", bytes_(x["D"]["median"]))
            mc.add(f"{w}DLow", opt(bytes_, x["D"]["ci95"][0]))
            mc.add(f"{w}DHigh", opt(bytes_, x["D"]["ci95"][1]))
        for role, parts in (x.get("parts") or {}).items():
            rw = "Server" if role == "server" else "Competitor"
            for key, kw in (("W", "W"), ("U", "U"), ("Kq", "Kq"), ("Ks_minus_K_BASE", "KsNet"), ("skb_growth", "SkbGrowth"),
                            ("shared_growth", "SharedGrowth"), ("f_mean", "F")):
                mc.add(f"{w}{rw}{kw}", opt(bytes_, parts.get(key)))
        for role, n in (x.get("listen_overflows") or {}).items():
            mc.add(f"{w}{role.capitalize()}ListenOverflows", count(n))


def claims(mc: Macros, s: dict) -> None:
    cl = s["claims"]["C"]
    mc.add("CostClaimCount", count(len(cl)))
    items = [f"{PROTO_TEXT[c['proto']]} on {c['backend']} ({c['host']})" for c in cl]
    mc.add("CostClaims", ", ".join(items[:-1]) + (" and " if len(items) > 1 else "") + (items[-1] if items else "none"))
    for c in cl:
        mc.add(f"{word(c['host'] + '.' + c['backend'] + '.' + c['proto'])}JointPower", opt(power, c.get("joint_power")))
    mc.add("BThreeClaimCount", count(len(s["claims"]["B3"])))
    mc.add("MClaimCount", count(len(s["claims"]["M"])))
    if s["k_base"]["K_BASE"] is not None:
        mc.add("KBase", bytes_(s["k_base"]["K_BASE"]), "WL7, bytes per pending connection")
    mc.add("BOneFailures", count(len(s["b1_failures"])), "misclassified connections in measured windows")


def secondary(mc: Macros, s: dict) -> None:
    for e in s["secondary"]:
        if e.get("interval") is None:
            continue
        w = "Sec" + word(e["bullet"]) + word(e["cell"]) + word(e["metric"])
        mc.add(f"{w}Median", ratio(e["median"]))
        mc.add(f"{w}Low", opt(ratio, e["interval"][0]))
        mc.add(f"{w}High", opt(ratio, e["interval"][1]))


def build(s: dict) -> str:
    mc = Macros()
    design(mc, s)
    family(mc, s, "C", "Cost")
    family(mc, s, "B3", "BThree")
    family(mc, s, "M", "M")
    claims(mc, s)
    secondary(mc, s)
    return (SYNTHETIC_HEAD if s.get("synthetic") else "") + HEAD + mc.text()


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("summary", type=Path)
    ap.add_argument("--out", type=Path, default=HERE.parent / "results" / "macros.tex")
    a = ap.parse_args(argv)
    s = json.loads(a.summary.read_text(encoding="utf-8"))
    if s.get("synthetic"):
        versions.refuse_results_path(a.out)
    text = build(s)
    a.out.parent.mkdir(parents=True, exist_ok=True)
    with open(a.out, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"macros: {text.count(chr(10)) - 1} lines to {a.out}" + (" (SYNTHETIC)" if s.get("synthetic") else ""))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
