#!/usr/bin/env python3
"""B2's distributions of lateness and decision latency (results/b2-macros.tex, results/tables/b2.tex).

    python paper/b2_macros.py --l HL1_HARDCASES.jsonl --w WH1_HARDCASES.jsonl [--check]

Frozen section 5.2: "The lateness of timed events and the decision latency are reported per backend
as distributions, and not tested." The revision log's entry "Section 10's four descriptive outputs
not yet reported, and their untimed windows on the frozen build (a reading)", item 3, says how, and
this file applies it. The hard-case runners write, per run (kind "hardcase"):
  lateness_ns                    the timed event's wait return less its deadline, in a run a timer ended;
  decision_ns_after_last_write   the end of the connection's detection less opcase's last write at or
                                 before it, on the same clock (WL8's decision time).
Per backend (epoll and io_uring from hl1 on L, IOCP from wh1 on W), every run of the backend that
holds the value, detection modes, dispatches and cases pooled; the decision latency apart for the
runs a timer ended and the others. Each distribution: count, minimum, median, 99th percentile (the
value at rank ceil(0.99 n) of the sorted values) and maximum. Nothing is tested or decided.

The inputs are the files results/hardcase-macros.tex names (its "% input:" lines), checked by
sha256 before they are read. Like the other generators in paper/, this lives outside analysis/,
which stays as at ANALYSIS_COMMIT.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import math
import re
import statistics
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
RESULTS = ROOT / "results"
OUT = RESULTS / "b2-macros.tex"
TABLE = RESULTS / "tables" / "b2.tex"
HARDCASE = RESULTS / "hardcase-macros.tex"
sys.path.insert(0, str(ROOT / "analysis"))

import macros as AM  # noqa: E402  analysis/macros.py, read only: its formatters and store

HEAD = ("% Generated by paper/b2_macros.py from the hard-case rows of hl1 (L) and wh1 (W), named below by\n"
        "% their sha256 (the revision log's entry of 2026-10-08 on section 10's four outputs, item 3). Do not edit.\n"
        "% Descriptive: B2's distributions, reported and not tested.\n")
TABLE_HEAD = "% Generated by paper/b2_macros.py. Do not edit.\n"
# Host, job and the backends its runner's entries hold, in the order the paper gives them.
HOSTS = (("L", "hl1", ("epoll", "io_uring")), ("W", "wh1", ("IOCP",)))
BACKEND_TEXT = {"epoll": "epoll", "io_uring": "io\\_uring", "IOCP": "IOCP"}
# The three distributions: macro word, unit, scale from nanoseconds, decimals, the table's label.
DISTS = (("Lateness", "ms", 1e6, 3, "lateness of a timed event"),
         ("DecisionBytes", "us", 1e3, 1, "decision latency, runs no timer ended"),
         ("DecisionTimer", "ms", 1e6, 3, "decision latency, runs a timer ended"))
STATS = ("N", "Min", "Median", "PNinetyNine", "Max")
UNIT_TEX = {"us": "$\\mu$s", "ms": "ms"}
# Appendix A's cases whose detection ends on the client's half-close (HC21) or reset (HC22), which
# come after its last write: within the runs no timer ended, their decision latency holds the
# client's pause. Counted apart only to say where the upper tail lies; the distributions are whole.
SHUT_CASES = ("HC21", "HC22")


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def named_inputs() -> dict[str, str]:
    """Host -> the sha256 of its hardcases.jsonl, as results/hardcase-macros.tex names it."""
    text = HARDCASE.read_text(encoding="utf-8")
    out = {}
    for host, job, _ in HOSTS:
        found = re.findall(rf"^% input: {host} {job} hardcases\.jsonl sha256 ([0-9a-f]{{64}})$", text, re.M)
        if len(found) != 1:
            raise ValueError(f"{HARDCASE.name} names {host}'s {job} hardcases.jsonl {len(found)} times, not once")
        out[host] = found[0]
    return out


def read_rows(path: Path, digest: str, what: str) -> list[dict]:
    got = sha256_file(path)
    if got != digest:
        raise ValueError(f"{what}: {path} has sha256 {got}, not the {digest} that {HARDCASE.name} names")
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def nearest_rank(sorted_values: list[int], q: float) -> int:
    """The value at rank ceil(q n), counting from 1, of values sorted in ascending order."""
    if not sorted_values:
        raise ValueError("no value")
    return sorted_values[max(1, math.ceil(q * len(sorted_values))) - 1]


def summary(values: list[int]) -> dict[str, float]:
    v = sorted(values)
    return {"N": len(v), "Min": v[0], "Median": statistics.median(v), "PNinetyNine": nearest_rank(v, 0.99), "Max": v[-1]}


def split(rows: list[dict], host: str, job: str, backends: tuple[str, ...]) -> dict[str, dict[str, list[int]]]:
    """Per backend, the three lists of nanoseconds. Refuses a row of another job, a development row,
    a backend outside the host's, and a run whose lateness and timed event disagree."""
    out = {b: {d[0]: [] for d in DISTS} | {"NoWrite": [], "Runs": [], "Shut": [], "Other": []} for b in backends}
    runs = 0
    for r in rows:
        if r.get("kind") != "hardcase":
            continue
        runs += 1
        if r.get("job") != job or r.get("development") is not False:
            raise ValueError(f"{host}: a row of job {r.get('job')!r}, development {r.get('development')!r}")
        b = r.get("backend")
        if b not in out:
            raise ValueError(f"{host}: a row of backend {b!r}, not one of {backends}")
        timed = bool(r.get("timed"))
        if ("lateness_ns" in r) != timed:
            raise ValueError(f"{host}: {r.get('id')} {r.get('entry')} r{r.get('replicate')}: lateness and timed event disagree")
        if timed:
            out[b]["Lateness"].append(int(r["lateness_ns"]))
        out[b]["Runs"].append(1)
        if "decision_ns_after_last_write" in r:
            v = int(r["decision_ns_after_last_write"])
            out[b]["DecisionTimer" if timed else "DecisionBytes"].append(v)
            if not timed:
                case_id = str(r.get("id", ""))
                out[b]["Shut" if case_id.startswith(SHUT_CASES) else "Other"].append((v, case_id))
        else:
            out[b]["NoWrite"].append(1)  # no write of opcase at or before the end of detection
    if not runs:
        raise ValueError(f"{host}: no hardcase row")
    return out


def case_list(ids: list[str]) -> str:
    """The distinct cases of Appendix A among variant ids, as the paper names them: HC02.h2c.k21 -> HC2."""
    nums = sorted({int(m.group(1)) for m in (re.match(r"HC(\d\d)", i) for i in ids) if m})
    if len(nums) != len({i[:4] for i in ids}):
        raise ValueError(f"a variant id that names no case: {ids}")
    names = [f"HC{n}" for n in nums]
    if not names:
        return "none"
    return names[0] if len(names) == 1 else ", ".join(names[:-1]) + " and " + names[-1]


def macro_word(backend: str) -> str:
    return AM.WORDS[backend]


def build(paths: dict[str, Path]) -> dict[Path, str]:
    digests = named_inputs()
    mc = AM.Macros()
    table = []
    inputs = []
    counts: dict[str, tuple[int, int, int]] = {}
    for host, job, backends in HOSTS:
        rows = read_rows(paths[host], digests[host], f"{host}'s {job} rows")
        inputs.append(f"% input: {host} {job} hardcases.jsonl sha256 {digests[host]}\n")
        per = split(rows, host, job, backends)
        for b in backends:
            mc.add(f"BTwoDist{macro_word(b)}Runs", AM.count(len(per[b]["Runs"])), f"{host} {b}: hard-case runs")
            mc.add(f"BTwoDist{macro_word(b)}NoWriteN", AM.count(len(per[b]["NoWrite"])),
                   f"{host} {b}: runs with no write before the end of detection, so no decision latency")
            shut, other = sorted(per[b]["Shut"]), sorted(per[b]["Other"])
            if not shut or not other:
                raise ValueError(f"{host} {b}: no run of HC21 or HC22, or no other run, that no timer ended")
            above = [cid for v, cid in other if v > shut[-1][0]]
            w = f"BTwoDist{macro_word(b)}DecisionBytes"
            mc.add(f"{w}ShutN", AM.count(len(shut)), f"{host} {b}: runs of HC21 and HC22 among those no timer ended")
            mc.add(f"{w}ShutMin", AM.fixed(shut[0][0] / 1e3, 1), f"{host} {b}: their smallest decision latency, us")
            mc.add(f"{w}ShutMax", AM.fixed(shut[-1][0] / 1e3, 1), f"{host} {b}: their largest decision latency, us")
            mc.add(f"{w}OtherMax", AM.fixed(other[-1][0] / 1e3, 1), f"{host} {b}: the other runs' largest decision latency, us")
            mc.add(f"{w}OtherAboveN", AM.count(len(above)), f"{host} {b}: other runs above the largest of HC21 and HC22")
            mc.add(f"{w}OtherAboveCases", case_list(above), f"{host} {b}: the cases of those runs")
            counts[b] = (len(per[b]["Runs"]), len(per[b]["NoWrite"]), len(shut))
            for word, unit, scale, places, label in DISTS:
                values = per[b][word]
                if not values:
                    raise ValueError(f"{host} {b}: no value of {word}")
                s = summary(values)
                name = f"BTwoDist{macro_word(b)}{word}"
                mc.add(f"{name}N", AM.count(s["N"]), f"{host} {b}: {label}, runs")
                for k in STATS[1:]:
                    mc.add(f"{name}{k}", AM.fixed(s[k] / scale, places), f"{host} {b}: {label}, {k}, {unit}")
                cells = " & ".join(f"\\{name}{k}" for k in STATS)
                unit_tex = UNIT_TEX[unit]
                table.append(f"{BACKEND_TEXT[b]} & {label} ({unit_tex}) & {cells} \\\\")
    if counts["epoll"] != counts["io_uring"]:
        raise ValueError(f"L's two backends differ in runs, runs with no write or HC21 and HC22 runs: {counts}; "
                         "the paper gives epoll's counts for each Linux backend")
    clash = set(mc.names) & other_names()
    if clash:
        raise ValueError(f"names another macro file holds: {sorted(clash)}")
    return {OUT: HEAD + "".join(inputs) + mc.text(), TABLE: TABLE_HEAD + "\n".join(table) + "\n"}


def other_names() -> set[str]:
    names: set[str] = set()
    for p in sorted(RESULTS.glob("*macros.tex")):
        if p != OUT:
            names |= set(re.findall(r"\\newcommand\{\\([A-Za-z]+)\}", p.read_text(encoding="utf-8")))
    return names


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--l", type=Path, required=True, help="hl1's hardcases.jsonl (L)")
    ap.add_argument("--w", type=Path, required=True, help="wh1's hardcases.jsonl (W)")
    ap.add_argument("--check", action="store_true", help="compare with the committed files, write nothing")
    a = ap.parse_args(argv)
    out = build({"L": a.l, "W": a.w})
    if a.check:
        stale = [p for p, t in out.items() if not p.exists() or p.read_text(encoding="utf-8") != t]
        for p in stale:
            print("differs:", p.relative_to(ROOT).as_posix())
        return 1 if stale else 0
    for p, t in out.items():
        p.parent.mkdir(parents=True, exist_ok=True)
        with open(p, "w", encoding="utf-8", newline="\n") as f:
            f.write(t)
    print(f"b2: {len(out)} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
