#!/usr/bin/env python3
"""The paper's design macros (results/design-macros.tex), read from the frozen and pinned files.

    python paper/design_macros.py [--out results/design-macros.tex] [--check-code]

The method half of the paper states the design: its constants, its rules and the versions it
pins. Every number it states comes from a macro (Papers CLAUDE.md: "Numbers in papers come only
from generated results/macros.tex"; hypotheses.md section 13). The results come from
analysis/macros.py; the design constants come from here. Nothing is typed in by hand: each macro
names its source file and a pattern that must match that file exactly once, so a value that is
not in its source, or is there twice, stops the run.

The sources:
  - hypotheses.md: the frozen text and its revision log, the only source of a design value;
  - bench/cmake/pins.cmake: the pinned versions of the libraries and competitors;
  - design/status.md and design/w-procedure.md: the hosts' processors and Windows' timer tick,
    as read on the hosts (records of a reading, not design values).

The generator lives in paper/, not in analysis/: the revision log records that no file of
analysis/ changed after ANALYSIS_COMMIT (entry "ANALYSIS_COMMIT, before the code freeze",
item 3), and the pilot names that commit again. A paper-only script there would break that
statement.

--check-code compares the frozen values with the constants the code holds for them and prints
each disagreement. It never changes an emitted value: the paper states the frozen text.

Names are letters only, as in analysis/macros.py, and none of them is a name analysis/macros.py
emits (paper/test_design_macros.py checks it), so both files can be loaded together.
"""

from __future__ import annotations

import argparse
import datetime as dt
import re
import sys
from dataclasses import dataclass
from pathlib import Path
from typing import Callable

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
HYP = ROOT / "hypotheses.md"
PINS = ROOT / "bench" / "cmake" / "pins.cmake"
STATUS = ROOT / "design" / "status.md"
WPROC = ROOT / "design" / "w-procedure.md"

HEAD = ("% Generated by paper/design_macros.py from hypotheses.md (frozen text and revision log),\n"
        "% bench/cmake/pins.cmake, design/status.md and design/w-procedure.md. Do not edit.\n"
        "% The results' macros are analysis/macros.py's (results/macros.tex).\n")


# ---------------------------------------------------------------- formatting


def grouped(s: str) -> str:
    """Thousands grouped by a thin comma, as analysis/macros.py groups them."""
    s = s.replace(",", "")
    whole, _, frac = s.partition(".")
    if len(whole) > 3:
        parts = []
        while len(whole) > 3:
            parts.insert(0, whole[-3:])
            whole = whole[:-3]
        whole = "{,}".join([whole] + parts)
    return whole + ("." + frac if frac else "")


def verbatim(s: str) -> str:
    return s


def iso_date(s: str) -> str:
    d = dt.date.fromisoformat(s)
    return f"{d.day} {d.strftime('%B')} {d.year}"


def power_of_two(s: str) -> str:
    return grouped(str(2 ** int(s)))


def listing(values: list[str]) -> str:
    """1, 2 and 3."""
    return ", ".join(values[:-1]) + " and " + values[-1]


# ---------------------------------------------------------------- the table


@dataclass(frozen=True)
class Spec:
    names: tuple[str, ...]      # one macro per capture group, in order
    source: Path
    pattern: str                # must match the whitespace-normalised source exactly once
    fmt: Callable[[str], str] = grouped
    note: str = ""


def S(names: str, source: Path, pattern: str, fmt: Callable[[str], str] = grouped, note: str = "") -> Spec:
    return Spec(tuple(names.split()), source, pattern, fmt, note)


H = HYP
V = verbatim

SPECS: list[Spec] = [
    # Words and section 1: hosts, timers, the table, budgets
    S("FrozenDate", H, r"Status: FROZEN (\d{4}-\d{2}-\d{2})\.", iso_date, "the hypotheses freeze"),
    S("ClangVersion GoVersion", H, r"frozen at kernel [\d.]+, clang ([\d.]+) and go([\d.]+)\.", V, "Words"),
    S("MsvcVersion", H, r"with MSVC ([\d.]+)\. Both run on loopback", V, "Words"),
    S("FwAlpha", H, r"α = ([\d.]+), family-wise and one-sided", V, "Words"),
    S("TimerS", H, r"T_hdr are (\d+) s\.", note="T_fb = T_dec = T_hdr, section 1"),
    S("PendTimerS", H, r"uses (\d+) s, so that no pending connection expires", note="every detection timer in B3"),
    S("TlsNeed", H, r"byte 5 = 0x01 \| (\d+) bytes \|", note="TLS decides at"),
    S("TlsRecordMax", H, r"a record length of at most 2\^(\d+); byte 5", power_of_two, note="2^14"),
    S("HtwocNeed", H, r"\| h2c \| the (\d+)-byte preface of RFC 9113 s3\.4, exactly \|"),
    S("HttpNeedMax", H, r"exactly one SP \| at most (\d+) bytes \|"),
    S("SshNeed", H, r"`SSH-` \(RFC 4253 s4\.2\) \| (\d+) bytes \|"),
    S("MqttRlMin MqttRlMax", H, r"byte 0 = 0x10; a Remaining Length of (\d+) to (\d+) bytes;"),
    S("MqttNeedMin MqttNeedMax", H, r"level 4 or 5 \| (\d+) to (\d+) bytes \|"),
    S("ProxyVtwoNeed ProxyVtwoMatch ProxyVoneNeed ProxyVoneMatch", H,
      r"v2 needs (\d+) bytes with the first (\d+) matching, v1 needs (\d+) with the first (\d+) equal to \"PROXY\""),
    S("ProxyVtwoMax", H, r"a v2 header longer than (\d+) bytes, the size both formats"),
    S("BDec", H, r"B_dec = (\d+) bytes after any PROXY header"),
    S("BCh", H, r"B_CH = (\d+) bytes for a ClientHello"),
    # Section 2: the server and the competitors
    S("NghttpVersion", H, r"h2 through nghttp2 \(v([\d.]+), the latest", V),
    S("OpensslSeries", H, r"OpenSSL from its ([\d.]+) LTS series", V),
    S("BodyBytes", H, r"\(200, `Content-Length: (\d+)`, body"),
    S("NginxVersion", H, r"\| nginx, stream module with `ssl_preread` \| ([\d.]+), built", V),
    S("HaproxyVersion", H, r"\| HAProxy \| ([\d.]+) \|", V),
    S("EnvoyVersion", H, r"\| Envoy \| ([\d.]+), the release binary", V),
    S("CaddyLfVersion CaddyLfCommit CaddyVersion", H,
      r"\| caddy-l4 \| (v[\d.]+) = commit ([0-9a-f]{40}), on Caddy (v[\d.]+), built", V),
    S("SslhVersion", H, r"\| sslh, the `sslh-ev` binary \| ([\d.]+) \|", V),
    S("NettyVersion", H, r"\| Netty \| ([\d.]+\.Final),", V),
    S("JettyVersion", H, r"\| Jetty \| ([\d.]+), on the same JDK", V),
    S("CmuxVersion", H, r"\| cmux \| (v[\d.]+) on go", V),
    S("HyperUtilVersion", H, r"\| hyper-util \| ([\d.]+) \|", V),
    # Section 3: workloads
    S("ConnSlots", H, r"C = (\d+) connection slots per server core"),
    S("RateFrac", H, r"`RATE_FRAC` = ([\d.]+), a design choice below saturation", V),
    S("OpenDonePct", H, r"fewer than (\d+)% of the exchanges due completed is invalid"),
    S("RateSessions", H, r"measured in (\d+) development sessions per cell on the frozen binary"),
    S("PendWindowS", H, r"Every B3 window lasts (\d+) s from the first connect"),
    S("PendOpenS", H, r"Opening, t = 0 to at most (\d+) s:"),
    S("NPend", H, r"`N_PEND` = ([\d,]+) connections \(a design choice\)"),
    S("PendBatch PendBatchMs", H, r"in batches of (\d+), one batch every (\d+) ms"),
    S("SslhBacklog", H, r"half of sslh's hard-coded backlog of (\d+)"),
    S("PendRate", H, r"the pace opens ([\d,]+) connections per second"),
    S("PendSettleS PendSettleGapS", H, r"Settling to t = (\d+) s, (\d+) s after the last batch"),
    S("SampleOneS SampleTwoS", H, r"Sample 1 at t = (\d+) s, sample 2 at t = (\d+) s"),
    S("KBaseWindows", H, r"over (\d+) windows is `K_BASE`"),
    # Section 4: statistics
    S("WarmupS MeasureS", H, r"then runs a (\d+) s warm-up and a (\d+) s measured window"),
    S("PlaceInprocServer PlaceInprocGenLo PlaceInprocGenHi", H,
      r"in-process cells, the server on CPU (\d+), `opgen` on CPUs (\d+) to (\d+);"),
    S("PlaceFront PlaceBackA PlaceBackB PlaceHandGenLo PlaceHandGenHi", H,
      r"hand-off cells, the front on CPU (\d+), the backend on CPUs (\d+) and (\d+), `opgen` on CPUs (\d+) to (\d+);"),
    S("PlaceTwoA PlaceTwoB PlaceTwoGenLo PlaceTwoGenHi", H,
      r"the 2-core secondary cells, the server on CPUs (\d+) and (\d+), `opgen` on CPUs (\d+) to (\d+)\."),
    S("PlaceSysA PlaceSysB", H, r"CPUs (\d+) and (\d+) for the system and the driver"),
    S("PlaceCaseSystem PlaceCaseBackA PlaceCaseBackB PlaceCaseLo PlaceCaseHi", H,
      r"B3 and hard cases, the system or `ophold` on CPU (\d+), its backend on CPUs (\d+) and (\d+), `opcase` on CPUs (\d+) to (\d+);"),
    S("EnvoyConnLimit", H, r"`per_connection_buffer_limit_bytes` (\d+) on the listener and the cluster"),
    S("EnvoyInitialRead", H, r"`initial_read_buffer_size` (\d+), the smallest value the proto accepts"),
    S("RepsBM RepsCap", H, r"R_B = R_M = (\d+) \(P2's reference, between the D9 minimum and (\d+), a design choice",
      note="R_B = R_M, and the cap it lies below"),
    S("BootResamples", H, r"as in P2: ([\d,]+) resamples"),
    S("BcaZzeroMax", H, r"only if \|z0\| < ([\d.]+)\.", V),
    S("MarginLow MarginHigh", H, r"between ([\d.]+) and ([\d.]+), for C1, C2 and C3", V),
    S("CostCellsMax", H, r"\| Cost \| at most (\d+), fixed by the pilot entry"),
    S("CostDnineMin", H, r"6\.94e-4 at m = 36 \| (\d+) \(2\^-11"),
    S("FootprintDnineMin", H, r"\| 1\.39e-3 \| (\d+) \(2\^-10"),
    S("MechDnineMin", H, r"\| 1\.25e-3 \| (\d+) \(2\^-10"),
    S("SignAllowedLow", H, r"\| 11 \| (\d+) \| 1/2048 = 4\.88e-4 \| 5\.86e-3 \|", note="sessions allowed beyond each bound at R_C = 11"),
    S("SignAllowedHigh", H, r"\| 31 \| (\d+) \| 942649", note="at R_C = 31"),
    S("SupTwoK SupThreeK", H, r"which clears α/k only for k ≤ (\d+); three give 697/65536 = 1\.06e-2, which clears it only for k ≤ (\d+)\."),
    S("PilotSessions", H, r"runs P = (\d+) sessions \(a design choice, the count of P2\)"),
    S("SilvermanA SilvermanB SilvermanC", H, r"b = ([\d.]+) × min\(1, IQR\(e\)/\(([\d.]+) s\)\) × P\^\(-1/(\d+)\)", V),
    S("ChiQuantile", H, r"q the ([\d.]+) quantile of the chi-square distribution", V),
    S("UpperBoundPct", H, r"the one-sided (\d+)% upper confidence bound under normality"),
    S("ChiQ SUFactor", H, r"q = ([\d.]+) and s_U = ([\d.]+) s;", V),
    S("NSim", H, r"the share of `N_SIM` = ([\d,]+) runs that pass"),
    S("NSimSe", H, r"its Monte Carlo standard error at 0\.80 is ([\d.]+)\)", V),
    S("CostCandidates", H, r"Candidates: R = ((?:\d+, ){5}\d+ and \d+), the values", V),
    S("CostCandMin", H, r"Candidates: R = (\d+), "),
    S("CostCandMax", H, r"Candidates: R = [\d, ]+ and (\d+), the values"),
    S("PowerTarget", H, r"Power_c\(31\) ≥ ([\d.]+)\. The target", V),
    S("RunsMax", H, r"\"not resolved at R ≤ (\d+)\""),
    S("FamilyBCells FamilyBDescriptive", H, r"### 6\.2 B3, (\d+) Holm cells and (\d+) descriptive cells"),
    S("FamilyMCells", H, r"### 6\.3 Mechanism family, (\d+) cells"),
    S("SilentHolmCells", H, r"silent case: nginx, HAProxy, Envoy, sslh-ev, hyper-util; each on epoll and io_uring \((\d+)\);",
      note="B3's silent-case Holm cells"),
    S("PartialHolmCells", H, r"partial-ClientHello case: nginx, HAProxy, Envoy, sslh-ev; each on epoll and io_uring \((\d+)\)\.",
      note="B3's partial-ClientHello Holm cells"),
    S("MechOneCells", H, r"h2c on epoll, io_uring, IOCP \((\d+); the IOCP cells on W\)"),
    S("MechTwoCells", H, r"TLS on epoll, io_uring \((\d+)\);"),
    S("MechThreeCells", H, r"against the same five, in the same order \((\d+)\)\."),
    S("CiPct", H, r"Each cost cell shows, beside its (\d+)% BCa interval"),
    S("SshSecCells", H, r"C1 to C3 on three backends \((\d+) cells\)"),
    S("MixedSecCells", H, r"the same in both modes, on each backend \((\d+) cells\)"),
    S("TlsSecCells", H, r"TLS with ALPN `h2`: C1 on each backend \((\d+) cells\)"),
    S("TwoCoreSecCells ReuseportSecCells", H,
      r"C1 HTTP/1\.1 on each backend \((\d+) cells\); and on epoll and io_uring the `SO_REUSEPORT` group against the shared listener, both in one-port mode \((\d+) cells\)"),
    S("RelaySecCells", H, r"The server's relay on io_uring against the proxies \((\d+) cells\)"),
    S("IocpSecCells", H, r"followed by the receive form rule E chose \((\d+) cells\)"),
    S("TtfbSecCells", H, r"For M1 and M3, TTFB at a fixed load \((\d+) cells\)"),
    S("OtherModeSecCells", H, r"in both cases on both Linux backends \((\d+) cells\), with Q = other / default"),
    S("ResumptionCells", H, r"\"TLS with session resumption: C1 on each backend\" \((\d+) cells\) is not run"),
    S("FootprintMargin", H, r"is at least ([\d.]+)\. By WL7 this ratio", V),
    S("MechBound", H, r"for M1 and M3 \"the median ratio is at most ([\d.]+)\"", V),
    # Section 7: validity
    S("ErrorSharePct", H, r"the error share exceeded ([\d.]+)%", V),
    S("GenBusyPct", H, r"the error share exceeded [\d.]+%, the generator's CPUs were more than (\d+)% busy"),
    S("MhzDriftPct", H, r"drifted more than (\d+)% from the session's value"),
    S("BackendBusyPct", H, r"a backend core was more than (\d+)% busy"),
    S("SettlePct", H, r"the larger of (\d+)% of sample 2's W"),
    S("SettleAbs", H, r"`SETTLE_ABS` = (\d+) bytes per pending connection"),
    S("TimeWaitS", H, r"TIME-WAIT sockets are slab objects and last (\d+) s"),
    # Section 8: freezes, rule E, the pilot's parts
    S("RuleESessions", H, r"every session of at least (\d+) development sessions of HTTP/1\.1 churn"),
    S("RuleEP", H, r"can reach p = 2\^-6 = ([\d.]+), below", V),
    S("TimerRuns", H, r"on each backend, (\d+) runs, one connection at a time"),
    S("SplitReps", H, r"(\d+) replicates \(the hard cases' replicate count\)"),
    S("SplitGaps", H, r"tested gap of ((?:\d+, ){3}\d+ and \d+) ms", V),
    S("PilotRerunCap", H, r"at most ⌈P/4⌉ = (\d+) times per cell"),
    # Section 10 and Appendix A
    S("ReplicatesSecondary", H, r"run at R = (\d+), a design choice \(P2's reference\)"),
    S("CompReps", H, r"`R_COMP_CASES` = (\d+) replicates per case"),
    S("TObsS TDefaultMaxS", H, r"`T_OBS` = (\d+) s, twice the longest default timer among the others \((\d+) s\)"),
    S("CaseReps", H, r"relay dispatch where it applies, (\d+) replicates\."),
    S("HardCases", H, r"\| (HC\d+) \| `GET key` and CRLF", lambda s: s[2:], note="the last case of Appendix A"),
    # Revision log: values set in engineering, the kernel, the analysis pins
    S("KernelL", H, r"the kernel names itself ([\w.\-]+), built", V, note="L after the host change"),
    S("KernelTag", H, r"all at Linux (v[\d.]+)\)", V, note="the tag of the cited kernel lines"),
    S("KSrc", H, r"`K_SRC` = (\d+) \(section 9\.1"),
    S("NAcceptex", H, r"`N_ACCEPTEX` = (\d+) \(`kAcceptEx`"),
    S("RelayBuf", H, r"`RELAY_BUF` = (\d+) bytes per direction \(`kRelayBuf`"),
    S("NBg", H, r"`N_BG_SILENT` = (\d+) \(the entry", note="N_BG_TLS = N_BG_MQTT = N_BG_SILENT"),
    S("HelloLen", H, r"ℓ = (\d+): the record length"),
    S("AnalysisCommit", H, r"`ANALYSIS_COMMIT` = ([0-9a-f]{40}), one-port's last", V),
    S("NumpyVersion PythonVersion", H, r"it pins numpy ([\d.]+) on Python ([\d.]+)", V),
    S("FrozenSeeds", H, r"the (\d+) names the frozen runners"),
    # pins.cmake
    S("OpensslVersion", PINS, r'set\(ONEPORT_OPENSSL_VERSION "([\d.]+)"\)', V),
    S("JdkVersion", PINS, r'set\(ONEPORT_JDK_VERSION "([\d.+]+)"\)', V),
    S("RustVersion", PINS, r'set\(ONEPORT_RUSTC_VERSION "([\d.]+)"\)', V),
    S("XcaddyVersion", PINS, r'set\(ONEPORT_XCADDY_VERSION "([\d.]+)"\)', V),
    # The hosts, as read on them
    S("HostLCpu HostLCpus HostLSmt", STATUS, r"\| Host \| `alex-laptop`, (AMD Ryzen 7 5800H), (\d+) CPUs, (\d+) threads per core \|", V),
    S("HostWCpu HostWCores HostWCpus", WPROC, r"\| CPU \| (AMD Ryzen 5 3600) 6-Core Processor; (\d+) cores, (\d+) logical processors;", V),
    S("HostWOs HostWBuild", WPROC, r"\| OS \| (Windows 11 Pro N), ([\d.]+) \|", V),
    S("WTickMs", WPROC, r"coarsest ([\d.]+) ms, finest", V, note="Windows' default timer resolution on W"),
]

# Versions that the frozen text and pins.cmake both name: they must agree.
PIN_CROSS = [
    ("NghttpVersion", r'set\(ONEPORT_NGHTTP2_VERSION "([\d.]+)"\)'),
    ("NginxVersion", r'set\(ONEPORT_NGINX_VERSION "([\d.]+)"\)'),
    ("HaproxyVersion", r'set\(ONEPORT_HAPROXY_VERSION "([\d.]+)"\)'),
    ("EnvoyVersion", r'set\(ONEPORT_ENVOY_VERSION "([\d.]+)"\)'),
    ("CaddyLfVersion", r'set\(ONEPORT_CADDY_L4_VERSION "(v[\d.]+)"\)'),
    ("CaddyLfCommit", r'set\(ONEPORT_CADDY_L4_COMMIT "([0-9a-f]{40})"\)'),
    ("CaddyVersion", r'set\(ONEPORT_CADDY_VERSION "(v[\d.]+)"\)'),
    ("SslhVersion", r'set\(ONEPORT_SSLH_VERSION "([\d.]+)"\)'),
    ("NettyVersion", r'set\(ONEPORT_NETTY_VERSION "([\w.]+)"\)'),
    ("JettyVersion", r'set\(ONEPORT_JETTY_VERSION "([\d.]+)"\)'),
    ("CmuxVersion", r'set\(ONEPORT_CMUX_VERSION "(v[\d.]+)"\)'),
    ("HyperUtilVersion", r'set\(ONEPORT_HYPER_UTIL_VERSION "([\d.]+)"\)'),
]

# Constants the code holds for a frozen value: (macro, file, pattern, how the code's value maps
# onto the macro's). A disagreement is printed; the macro keeps the frozen value.
CODE_CROSS = [
    ("BDec", "bench/server/detect.hpp", r"kBDec = (\d+);", str),
    ("BCh", "bench/server/detect.hpp", r"kBCh = (\d+);", str),
    ("ProxyVtwoMax", "bench/server/detect.hpp", r"kProxyV2Max = (\d+);", str),
    ("TlsRecordMax", "bench/server/detect.hpp", r"kTlsRecordMax = (\d+);", str),
    ("TlsNeed", "bench/server/detect.hpp", r"make\(Proto::tls, &match_tls, (\d+), \d+\)", str),
    ("HtwocNeed", "bench/server/detect.hpp", r"make\(Proto::h2c, &match_h2c, (\d+), \d+\)", str),
    ("HttpNeedMax", "bench/server/detect.hpp", r"make\(Proto::http1, &match_http1, \d+, (\d+)\)", str),
    ("SshNeed", "bench/server/detect.hpp", r"make\(Proto::ssh, &match_ssh, (\d+), \d+\)", str),
    ("MqttNeedMin", "bench/server/detect.hpp", r"make\(Proto::mqtt, &match_mqtt, (\d+), \d+\)", str),
    ("MqttNeedMax", "bench/server/detect.hpp", r"make\(Proto::mqtt, &match_mqtt, \d+, (\d+)\)", str),
    ("TimerS", "bench/server/config.hpp", r"kDesignTimerMs = (\d+);", lambda ms: str(int(ms) // 1000)),
    ("NAcceptex", "bench/server/worker.hpp", r"kAcceptEx = (\d+);", str),
    ("RelayBuf", "bench/server/server.hpp", r"kRecvBuf = (\d+);", str),
]


# ---------------------------------------------------------------- reading


def normalised(path: Path) -> str:
    return " ".join(path.read_text(encoding="utf-8").split())


class SourceError(RuntimeError):
    pass


def match_once(text: str, pattern: str, where: str) -> re.Match:
    found = list(re.finditer(pattern, text))
    if len(found) != 1:
        raise SourceError(f"{where}: pattern {pattern!r} matches {len(found)} times, not once")
    return found[0]


def read_specs(specs: list[Spec] = SPECS) -> list[tuple[str, str, str]]:
    """(name, value, note) for every macro, in table order."""
    texts: dict[Path, str] = {}
    out: list[tuple[str, str, str]] = []
    for spec in specs:
        text = texts.setdefault(spec.source, normalised(spec.source))
        m = match_once(text, spec.pattern, spec.source.name)
        groups = m.groups()
        if len(groups) != len(spec.names):
            raise SourceError(f"{spec.names}: {len(groups)} groups for {len(spec.names)} names")
        for name, raw in zip(spec.names, groups):
            note = spec.source.relative_to(ROOT).as_posix() + (f", {spec.note}" if spec.note else "")
            out.append((name, spec.fmt(raw.strip().rstrip(",")), note))
    return out


def values_of(items: list[tuple[str, str, str]]) -> dict[str, str]:
    return {n: v for n, v, _ in items}


def plain(v: str) -> str:
    return v.replace("{,}", "")


def pin_disagreements(values: dict[str, str]) -> list[str]:
    text = normalised(PINS)
    out = []
    for name, pattern in PIN_CROSS:
        pinned = match_once(text, pattern, PINS.name).group(1)
        if pinned != values[name]:
            out.append(f"{name}: hypotheses.md says {values[name]}, pins.cmake says {pinned}")
    return out


def code_disagreements(values: dict[str, str]) -> list[str]:
    out = []
    for name, rel, pattern, conv in CODE_CROSS:
        code = conv(match_once(normalised(ROOT / rel), pattern, rel).group(1))
        if code != plain(values[name]):
            out.append(f"{name}: hypotheses.md says {plain(values[name])}, {rel} holds {code}")
    return out


# ---------------------------------------------------------------- writing


DASHES = "\u2010\u2011\u2012\u2013\u2014\u2015\u2212\ufe58\ufe63\uff0d"


def render(items: list[tuple[str, str, str]]) -> str:
    seen: set[str] = set()
    lines = [HEAD]
    for name, value, note in items:
        if not re.fullmatch(r"[A-Za-z]+", name):
            raise ValueError(f"macro name {name!r} is not letters only")
        if name in seen:
            raise ValueError(f"macro {name} defined twice")
        if any(c in value for c in DASHES) or "--" in value:
            raise ValueError(f"macro {name}'s value {value!r} holds a dash")
        seen.add(name)
        lines.append(f"\\newcommand{{\\{name}}}{{{value}}}  % {note}\n")
    return "".join(lines)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--out", type=Path, default=ROOT / "results" / "design-macros.tex")
    ap.add_argument("--check-code", action="store_true", help="print where the code's constants differ from the frozen values")
    a = ap.parse_args(argv)
    items = read_specs()
    values = values_of(items)
    pins = pin_disagreements(values)
    if pins:
        for p in pins:
            print("pins disagree:", p, file=sys.stderr)
        return 1
    if a.check_code:
        diffs = code_disagreements(values)
        for d in diffs:
            print("code differs:", d)
        print(f"check-code: {len(CODE_CROSS)} constants compared, {len(diffs)} differ")
    text = render(items)
    a.out.parent.mkdir(parents=True, exist_ok=True)
    with open(a.out, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"design macros: {len(items)} to {a.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
