#!/usr/bin/env python3
"""B1's and B2's counts and decisions from the hard-case runners' outputs (results/hardcase-macros.tex).

    python paper/hardcase_macros.py --server L hl1 HARDCASES.jsonl TABLE.json \
                                    --server W wh1 HARDCASES.jsonl TABLE.json \
                                    --summary results/summary.json [--out results/hardcase-macros.tex]

B1 and B2 are deterministic (hypotheses.md 5.2): the hard-case runners judge each run with the
frozen suite's checks and write one row per run (kind "hardcase") with its B1 deviations (`b1`)
and the B2 checks that failed (`b2_failed`), one row per server at the end of an entry (kind
"hardcase-servers"), and a table of the runs per variant and entry. analysis/ reads none of them
(its not_produced list). The revision log's entry "B1's and B2's decisions from the hard-case
runners' outputs (a reading)", item 3, says how they are read, and this file applies it:
  B1 holds when no hardcase row of any server part has a non-empty `b1`, every variant and entry
     ran its 16 replicates with one row each, and summary.json's `b1_failures` (the measured
     windows, B1's second sentence) is empty;
  B2 holds when no hardcase row has a non-empty `b2_failed`;
  the server checks are counted beside them.
The table counts only the runs that reached the judge and passed both B1 and B2, so the counts
come from the rows and the table is checked against them. Each row is checked too: `b2_failed`
lists the failed checks of `b2`, `passed` agrees with `b1` and `b2_failed`, and a run that did
not reach the judge fails with its reason in `b1`. A host's entries are its runner's list
(ENTRIES in hardcase_run.py, ENTRIES_W in whardcase_run.py), and each entry must run every
variant the host ran, 16 replicates each. An input that disagrees stops the run.

Like paper/design_macros.py, this lives outside analysis/, which stays as at ANALYSIS_COMMIT. Names
are letters only and none is a name analysis/macros.py or paper/design_macros.py writes
(paper/test_hardcase_macros.py checks it). Every input is named in the output by its sha256.
"""

from __future__ import annotations

import argparse
import ast
import hashlib
import json
import re
import sys
from dataclasses import dataclass, field
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
REPLICATES = 16                     # 5.2, B1: "16 replicates"
CODE_FREEZE = "ff2679cc89d23e08a817308c9aeba7901e056fef"
# Per host: the runner that writes its rows, and the runner's list of entries (backend, detection
# mode, dispatch), read from the runner's source so that a missing entry is seen.
RUNNER_OF = {"L": ("hardcase_run", ROOT / "bench" / "run" / "hardcase_run.py", "ENTRIES"),
             "W": ("whardcase_run", ROOT / "bench" / "run" / "whardcase_run.py", "ENTRIES_W")}
ENTRY_TITLE = "B1's and B2's decisions from the hard-case runners' outputs (a reading)"

HEAD = ("% Generated by paper/hardcase_macros.py from the hard-case runners' outputs and summary.json's\n"
        f"% b1_failures (revision log, \"{ENTRY_TITLE}\"). Do not edit.\n")


class InputRefused(RuntimeError):
    pass


@dataclass(frozen=True)
class HostCounts:
    host: str
    job: str
    entries: int
    variant_entries: int
    runs: int
    passed: int
    b1_deviations: int
    b2_failures: int
    incomplete: int
    woke_more_than_once: int
    server_checks: int
    server_checks_ok: int
    details: tuple[str, ...] = field(default=())


# ---------------------------------------------------------------- reading


def sha256_file(path: Path) -> str:
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def read_rows(path: Path) -> list[dict]:
    return [json.loads(ln) for ln in Path(path).read_text(encoding="utf-8").splitlines() if ln.strip()]


def runner_entries(host: str) -> tuple[str, ...]:
    """The runner's tuple of entries, evaluated from its assignment in the runner's source (a
    comprehension over literals), so this file never imports the runner."""
    _, path, name = RUNNER_OF[host]
    for node in ast.parse(path.read_text(encoding="utf-8")).body:
        if isinstance(node, ast.Assign) and [getattr(t, "id", None) for t in node.targets] == [name]:
            return tuple(eval(compile(ast.Expression(node.value), str(path), "eval"), {"__builtins__": {"tuple": tuple}}))
    raise InputRefused(f"{path.name} assigns no {name}")


def check_row(row: dict, host: str, job: str) -> None:
    where = f"{row.get('kind')} {row.get('entry')} {row.get('id', row.get('server'))} r{row.get('replicate')}"
    if row.get("kind") not in ("hardcase", "hardcase-servers"):
        raise InputRefused(f"{where}: kind {row.get('kind')!r} is not a server part's")
    if row.get("job") != job:
        raise InputRefused(f"{where}: job {row.get('job')!r}, not {job}")
    if row.get("development") is not False:
        raise InputRefused(f"{where}: not a frozen run (development {row.get('development')!r})")
    if row.get("runner") != RUNNER_OF[host][0] or row.get("host", host) != host:
        raise InputRefused(f"{where}: runner {row.get('runner')!r} on host {row.get('host', host)!r}, not {host}'s")
    cf = (((row.get("provenance") or {}).get("freeze") or {}).get("freeze") or {}).get("code_freeze")
    if cf != CODE_FREEZE:
        raise InputRefused(f"{where}: provenance names code_freeze {cf!r}, not CODE_FREEZE")
    if row["kind"] != "hardcase":
        return
    b1, judged = row.get("b1"), "b2_failed" in row
    if not isinstance(b1, list):
        raise InputRefused(f"{where}: b1 is not a list")
    if judged:
        failed = row["b2_failed"]
        b2 = row.get("b2")
        if not isinstance(failed, list) or not isinstance(b2, dict) or failed != sorted(k for k, v in b2.items() if v):
            raise InputRefused(f"{where}: b2_failed does not list the failed checks of b2")
        if bool(row.get("passed")) != (not b1 and not failed):
            raise InputRefused(f"{where}: passed disagrees with b1 and b2_failed")
    elif not b1 or row.get("passed"):
        raise InputRefused(f"{where}: a run that did not reach the judge must fail with its reason in b1")


def host_counts(host: str, job: str, rows: list[dict], table: dict) -> HostCounts:
    if host not in RUNNER_OF:
        raise InputRefused(f"host {host!r}: the server parts are L's and W's")
    for r in rows:
        check_row(r, host, job)
    runs = [r for r in rows if r["kind"] == "hardcase"]
    servers = [r for r in rows if r["kind"] == "hardcase-servers"]
    seen: dict[str, set[int]] = {}
    for r in runs:
        reps = seen.setdefault(f"{r['entry']}|{r['id']}", set())
        if r["replicate"] in reps:
            raise InputRefused(f"{host}: {r['entry']} {r['id']} r{r['replicate']} has two rows")
        reps.add(r["replicate"])
    judged = [r for r in runs if "b2_failed" in r]   # a run that reached the judge (the runner's table counts these)
    want: dict[str, dict] = {}
    for r in judged:
        t = want.setdefault(f"{r['entry']}|{r['id']}", {"runs": 0, "passed": 0, "woke_twice": 0})
        t["runs"] += 1
        t["passed"] += int(bool(r.get("passed")))
        t["woke_twice"] += int((r.get("wakeups") or 0) >= 2)
    got = {k: {x: v[x] for x in ("runs", "passed", "woke_twice")} for k, v in table.items()}
    if got != want:
        bad = sorted(k for k in set(got) | set(want) if got.get(k) != want.get(k))
        raise InputRefused(f"{host}: the table and the rows disagree at {len(bad)} variant-entries, first {bad[:3]}")
    entries = runner_entries(host)
    unknown = sorted({r["entry"] for r in runs} - set(entries))
    if unknown:
        raise InputRefused(f"{host}: entries {unknown} are not in {RUNNER_OF[host][1].name}'s list")
    # Every entry runs every variant the host ran (5.2: every backend, both detection modes, every
    # dispatch mode); a variant missing on every entry of a host cannot be seen without the frozen
    # case list, which is compiled into opcase.
    variants = sorted({r["id"] for r in runs})
    expected = {f"{e}|{v}" for e in entries for v in variants}
    full = set(range(1, REPLICATES + 1))
    incomplete = sorted(k for k in expected if seen.get(k, set()) != full)
    details = [f"{host} {r['entry']} {r['id']} r{r['replicate']}: b1={r.get('b1')} b2_failed={r.get('b2_failed', [])}"
               for r in runs if r.get("b1") or r.get("b2_failed")]
    details += [f"{host} {k}: replicates {sorted(seen.get(k, set()))}" for k in incomplete]
    details += [f"{host} server {s.get('entry')} {s.get('server')}: {s.get('problems')}" for s in servers if not s.get("ok")]
    return HostCounts(host=host, job=job, entries=len({r["entry"] for r in runs}), variant_entries=len(expected), runs=len(runs),
                      passed=sum(1 for r in runs if r.get("passed")), b1_deviations=sum(1 for r in runs if r.get("b1")),
                      b2_failures=sum(1 for r in runs if r.get("b2_failed")), incomplete=len(incomplete),
                      woke_more_than_once=sum(v["woke_twice"] for v in table.values()), server_checks=len(servers),
                      server_checks_ok=sum(1 for s in servers if s.get("ok") is True),
                      details=tuple(" ".join(d.split()) for d in details))


# ---------------------------------------------------------------- writing


def grouped(n: int) -> str:
    """Thousands grouped by a thin comma, as analysis/macros.py groups them."""
    s = str(int(n))
    parts = []
    while len(s) > 3:
        parts.insert(0, s[-3:])
        s = s[:-3]
    return "{,}".join([s] + parts)


def items(hosts: list[HostCounts], b1_measured: int) -> list[tuple[str, str, str]]:
    out: list[tuple[str, str, str]] = []
    for h in hosts:
        p = f"Hardcase{h.host}"
        out += [(f"{p}Entries", grouped(h.entries), f"{h.job}: backend, detection mode and dispatch"),
                (f"{p}VariantEntries", grouped(h.variant_entries), "the host's variants of Appendix A's cases times the runner's entries"),
                (f"{p}Runs", grouped(h.runs), "rows of kind hardcase"),
                (f"{p}Passed", grouped(h.passed), "runs that passed B1 and B2"),
                (f"{p}BOneDeviations", grouped(h.b1_deviations), "runs with a B1 deviation"),
                (f"{p}BTwoFailures", grouped(h.b2_failures), "runs with a failed B2 check"),
                (f"{p}Incomplete", grouped(h.incomplete), "variant-entries without their 16 replicates"),
                (f"{p}WokeMoreThanOnce", grouped(h.woke_more_than_once), "runs whose detection woke more than once (the table's woke_twice)"),
                (f"{p}ServerChecks", grouped(h.server_checks), "rows of kind hardcase-servers"),
                (f"{p}ServerChecksOk", grouped(h.server_checks_ok), "server checks that are ok")]
    out += [("HardcaseRuns", grouped(sum(h.runs for h in hosts)), "all hosts"),
            ("HardcasePassed", grouped(sum(h.passed for h in hosts)), "all hosts"),
            ("HardcaseBOneDeviations", grouped(sum(h.b1_deviations for h in hosts)), "all hosts"),
            ("HardcaseBTwoFailures", grouped(sum(h.b2_failures for h in hosts)), "all hosts")]
    b1 = all(h.b1_deviations == 0 and h.incomplete == 0 for h in hosts) and b1_measured == 0
    b2 = all(h.b2_failures == 0 for h in hosts)
    out += [("BOneVerdict", "holds" if b1 else "does not hold", "hard cases and summary.json's b1_failures (5.2)"),
            ("BTwoVerdict", "holds" if b2 else "does not hold", "hard cases (5.2)")]
    return out


def render(entries: list[tuple[str, str, str]], inputs: list[tuple[str, str]], details: list[str]) -> str:
    seen: set[str] = set()
    lines = [HEAD] + [f"% input: {what} sha256 {digest}\n" for what, digest in inputs]
    lines += [f"% deviation: {d}\n" for d in details]
    for name, value, note in entries:
        if not re.fullmatch(r"[A-Za-z]+", name):
            raise ValueError(f"macro name {name!r} is not letters only")
        if name in seen:
            raise ValueError(f"macro {name} defined twice")
        seen.add(name)
        lines.append(f"\\newcommand{{\\{name}}}{{{value}}}  % {note}\n")
    return "".join(lines)


def build(servers: list[tuple[str, str, Path, Path]], summary: Path) -> str:
    hosts, inputs, details = [], [], []
    if len({h for h, _, _, _ in servers}) != len(servers) or not all(re.fullmatch(r"[A-Z]", h) for h, _, _, _ in servers):
        raise InputRefused("each --server needs its own host letter (L, W)")
    for host, job, rows_path, table_path in servers:
        table = json.loads(Path(table_path).read_text(encoding="utf-8"))
        hc = host_counts(host, job, read_rows(rows_path), table)
        hosts.append(hc)
        details += list(hc.details)
        inputs += [(f"{host} {job} {Path(rows_path).name}", sha256_file(rows_path)),
                   (f"{host} {job} {Path(table_path).name}", sha256_file(table_path))]
    s = json.loads(Path(summary).read_text(encoding="utf-8"))
    if s.get("synthetic") is not False or not isinstance(s.get("b1_failures"), list):
        raise InputRefused("summary.json is synthetic or has no b1_failures list")
    inputs.append((f"{Path(summary).name} (b1_failures)", sha256_file(summary)))
    return render(items(hosts, len(s["b1_failures"])), inputs, details)


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--server", nargs=4, action="append", required=True, metavar=("HOST", "JOB", "ROWS", "TABLE"),
                    help="a server part: host letter, lab job, its hardcases.jsonl and hardcases-table-JOB.json")
    ap.add_argument("--summary", type=Path, required=True, help="the confirmatory analysis's summary.json (b1_failures)")
    ap.add_argument("--out", type=Path, default=ROOT / "results" / "hardcase-macros.tex")
    a = ap.parse_args(argv)
    try:
        text = build([(h, j, Path(r), Path(t)) for h, j, r, t in a.server], a.summary)
    except InputRefused as e:
        print(f"hardcase_macros.py: refused: {e}", file=sys.stderr)
        return 2
    a.out.parent.mkdir(parents=True, exist_ok=True)
    with open(a.out, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"hardcase macros: {text.count(chr(92) + 'newcommand')} to {a.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
