#!/usr/bin/env python3
"""Operations and copies per connection (WL5) from the measured windows (results/ops-macros.tex,
results/tables/ops-cost.tex, results/tables/ops-m1.tex).

    python paper/ops_macros.py --cost-l COST_L.jsonl --cost-w COST_W.jsonl --m-l M_L.jsonl --m-w M_W.jsonl [--check]

Frozen section 10: "Operations and copies per connection for every mode and backend"; WL5: "The
counters of 2.1 per connection", read by item 6 of the entry "Readings fixed during engineering
(M3)" as a window's server process's counters over its life divided by the connections it accepted,
and for keep-alive also per request. The revision log's entry "Section 10's four descriptive outputs
not yet reported, and their untimed windows on the frozen build (a reading)", item 4, says where each
mode is read, and this file applies its parts (i) and (ii):
  (i)  in-process, one-port and dedicated mode, replay: every cost cell and arm (pc1 on L, wc1 and
       wc2 on W);
  (ii) in-process, one-port, replay and peek: M1's cells (ml1 on L, wm1 on W).
Part (iii), the relay in both detection modes, comes from the untimed rows of lab job st1
(paper/trace_macros.py). Per arm: the mean over its valid windows of each window's `per_connection`
value, in keep-alive (C2) per request; operations are rule E's sum (bench/run/rule_e.py's
OP_COUNTERS and io_uring's submissions by opcode); copies are `bytes_copied` (in user space) and
`bytes_received`, `bytes_sent` and `bytes_peeked` (across the boundary); and `detection_wakeups`.
No interval and no ratio: the two arms stand side by side. Every input is checked against the sha256
that results/summary.json names for it before it is read. This lives in paper/, as the other
generators do, because analysis/ stays as at ANALYSIS_COMMIT.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import statistics
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
RESULTS = ROOT / "results"
SUMMARY = RESULTS / "summary.json"
OUT = RESULTS / "ops-macros.tex"
TABLES = RESULTS / "tables"
sys.path.insert(0, str(ROOT / "analysis"))

import macros as AM  # noqa: E402  analysis/macros.py, read only: its formatters and store

HEAD = ("% Generated by paper/ops_macros.py from the cost family's and M1's window rows, named below by their\n"
        "% sha256 (results/summary.json's inputs). Do not edit. Descriptive: WL5, the revision log's entry of\n"
        "% 2026-10-08 on section 10's four outputs, item 4 (i) and (ii).\n")
TABLE_HEAD = "% Generated by paper/ops_macros.py. Do not edit.\n"
# bench/run/rule_e.py's OP_COUNTERS: the call counters by kind whose sum, with io_uring's submissions
# by opcode, is rule E's operations per connection (design/status.md, M7c). Read from the source below.
RULE_E = ROOT / "bench" / "run" / "rule_e.py"
METRICS = (("Ops", None, 3), ("Copied", "bytes_copied", 1), ("Received", "bytes_received", 1), ("Sent", "bytes_sent", 1),
           ("Peeked", "bytes_peeked", 1), ("Wakeups", "detection_wakeups", 3))
COST_ARMS = (("one-port", "OnePort"), ("dedicated", "Dedicated"))
M1_ARMS = (("replay", "Replay"), ("peek", "Peek"))
PROTO = {"http1": "HTTP/1.1", "h2c": "h2c", "tls": "TLS", "mqtt": "MQTT"}
HOST_ORDER = ("L", "W")
BACKEND_ORDER = ("epoll", "io_uring", "IOCP")
PROTO_ORDER = ("http1", "h2c", "tls", "mqtt")


def op_counters() -> tuple[str, ...]:
    text = RULE_E.read_text(encoding="utf-8")
    m = re.search(r"^OP_COUNTERS = \(([^)]*)\)", text, re.M | re.S)
    if not m:
        raise ValueError(f"{RULE_E} defines no OP_COUNTERS")
    names = tuple(re.findall(r'"([a-z_]+)"', m.group(1)))
    if len(names) != 14:
        raise ValueError(f"OP_COUNTERS holds {len(names)} names, not the 14 of rule E's reading")
    return names


OP_COUNTERS = op_counters()


def sha256_file(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def summary_inputs() -> set[str]:
    return {i["sha256"] for i in json.loads(SUMMARY.read_text(encoding="utf-8"))["inputs"]}


def read_rows(path: Path, allowed: set[str], what: str) -> tuple[list[dict], str]:
    digest = sha256_file(path)
    if digest not in allowed:
        raise ValueError(f"{what}: {path} has sha256 {digest}, which results/summary.json does not name")
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()], digest


def ops(per: dict) -> float:
    """Rule E's operations: the call counters by kind and io_uring's submissions by opcode."""
    n = sum(float(per.get(k) or 0) for k in OP_COUNTERS)
    return n + sum(float(v) for v in (per.get("io_uring_submissions") or {}).values())


def window_values(r: dict) -> dict[str, float]:
    """One valid window's WL5 values: per connection, or per request in keep-alive. A keep-alive
    window's per-request value of a count is its per-connection value times its connections per
    request (`per_request.accepted`), which is how `per_request` is formed from the same counters."""
    per = r.get("per_connection")
    if not per or not per.get("accepted"):
        raise ValueError(f"{r.get('tag')}: a valid window without per_connection")
    scale = 1.0
    if r.get("workload") == "keepalive":
        pr = r.get("per_request")
        if not pr:
            raise ValueError(f"{r.get('tag')}: a keep-alive window without per_request")
        scale = float(pr["accepted"])
        for k in ("recv_calls", "send_calls", "bytes_received"):
            if abs(float(per.get(k, 0)) * scale - float(pr.get(k, 0))) > 1e-9 * max(1.0, abs(float(pr.get(k, 0)))):
                raise ValueError(f"{r.get('tag')}: per_request.{k} is not per_connection.{k} times per_request.accepted")
    out = {"Ops": ops(per) * scale}
    for word, key, _ in METRICS[1:]:
        out[word] = float(per.get(key) or 0) * scale
    return out


def arm_means(rows: list[dict], cell: str, key: str, value: str) -> tuple[int, dict[str, float]]:
    valid = [r for r in rows if r.get("cell") == cell and r.get(key) == value and r.get("valid") is True]
    if not valid:
        raise ValueError(f"{cell}: no valid window with {key} {value}")
    if any(r.get("development") is not False or r.get("dispatch") != "inproc" for r in valid):
        raise ValueError(f"{cell}: a development window, or a window not in-process")
    vals = [window_values(r) for r in valid]
    return len(valid), {w: statistics.fmean(v[w] for v in vals) for w, _, _ in METRICS}


def cell_order(cells: set[str]) -> list[str]:
    def key(c: str) -> tuple:
        h, host, backend, proto = c.split(".")
        return (h, HOST_ORDER.index(host), BACKEND_ORDER.index(backend), PROTO_ORDER.index(proto))
    return sorted(cells, key=key)


def add_arm(mc: AM.Macros, name: str, n: int, means: dict[str, float], note: str) -> None:
    mc.add(f"{name}Windows", AM.count(n), f"{note}: valid windows")
    for word, _, places in METRICS:
        mc.add(f"{name}{word}", AM.fixed(means[word], places), f"{note}: {word.lower()}")


def cell_text(cell: str) -> str:
    h, host, backend, proto = cell.split(".")
    return f"{h} & {host}, {AM.tex_text(backend)} & {PROTO[proto]}"


def cost_part(mc: AM.Macros, rows: list[dict]) -> list[str]:
    table = []
    for cell in cell_order({r["cell"] for r in rows if r.get("family") == "C" or r["cell"][:2] in ("C1", "C2", "C3")}):
        w = "WlFive" + AM.word(cell)
        per = "request" if cell.startswith("C2") else "connection"
        for mode, mw in COST_ARMS:
            n, means = arm_means(rows, cell, "mode", mode)
            if any(r.get("detect") != "replay" for r in rows if r.get("cell") == cell):
                raise ValueError(f"{cell}: a window not in replay")
            add_arm(mc, w + mw, n, means, f"{cell}, {mode}, per {per}")
        cols = [f"\\{w}OnePortWindows/\\{w}DedicatedWindows"]
        for word in ("Ops", "Copied", "Received", "Sent"):
            cols += [f"\\{w}OnePort{word}", f"\\{w}Dedicated{word}"]
        table.append(f"{cell_text(cell)} & " + " & ".join(cols) + " \\\\")
    return table


def m1_part(mc: AM.Macros, rows: list[dict]) -> list[str]:
    table = []
    for cell in cell_order({r["cell"] for r in rows if r["cell"].startswith("M1.")}):
        w = "WlFive" + AM.word(cell)
        _, host, backend, proto = cell.split(".")
        for detect, dw in M1_ARMS:
            if any(r.get("mode") != "one-port" for r in rows if r.get("cell") == cell):
                raise ValueError(f"{cell}: a window not in one-port mode")
            n, means = arm_means(rows, cell, "detect", detect)
            add_arm(mc, w + dw, n, means, f"{cell}, {detect}, per connection")
            cols = [f"\\{w}{dw}{k}" for k in ("Windows", "Ops", "Copied", "Received", "Sent", "Peeked", "Wakeups")]
            table.append(f"{host}, {AM.tex_text(backend)} & {PROTO[proto]} & {detect} & " + " & ".join(cols) + " \\\\")
    return table


def summary_macros(mc: AM.Macros) -> None:
    """Over the cost cells: the largest difference between the arms in operations, per connection
    in C1 and C3 and per request in C2, and the largest bytes copied in user space and peeked in any
    arm. Read from the values already in the store, so they say only what the table shows."""
    vals = {n: float(v.replace("{,}", "")) for n, v, _ in mc.items}
    diffs = {"Conn": [], "Req": []}
    copied, peeked = [], []
    for n in vals:
        m = re.fullmatch(r"WlFive(C(?:One|Two|Three)[A-Za-z]+?)OnePortOps", n)
        if m:
            d = abs(vals[n] - vals[f"WlFive{m.group(1)}DedicatedOps"])
            diffs["Req" if m.group(1).startswith("CTwo") else "Conn"].append(d)
        if re.fullmatch(r"WlFiveC(?:One|Two|Three)[A-Za-z]+(?:OnePort|Dedicated)Copied", n):
            copied.append(vals[n])
        if re.fullmatch(r"WlFiveC(?:One|Two|Three)[A-Za-z]+(?:OnePort|Dedicated)Peeked", n):
            peeked.append(vals[n])
    mc.add("WlFiveCostCells", AM.count(len(diffs["Conn"]) + len(diffs["Req"])), "cost cells with WL5 values")
    mc.add("WlFiveCostOpsMaxDiffConn", AM.fixed(max(diffs["Conn"]), 3),
           "C1 and C3: largest |one-port - dedicated| in operations per connection, as printed")
    mc.add("WlFiveCostOpsMaxDiffReq", AM.fixed(max(diffs["Req"]), 3),
           "C2: largest |one-port - dedicated| in operations per request, as printed")
    mc.add("WlFiveCostCopiedMax", AM.fixed(max(copied), 1), "largest bytes copied in user space in any cost arm")
    mc.add("WlFiveCostPeekedMax", AM.fixed(max(peeked), 1), "largest bytes peeked in any cost arm")


def other_names() -> set[str]:
    names: set[str] = set()
    for p in sorted(RESULTS.glob("*macros.tex")):
        if p != OUT:
            names |= set(re.findall(r"\\newcommand\{\\([A-Za-z]+)\}", p.read_text(encoding="utf-8")))
    return names


def build(paths: dict[str, Path]) -> dict[Path, str]:
    allowed = summary_inputs()
    rows: dict[str, list[dict]] = {}
    inputs = []
    for key, what in (("cost_l", "pc1 cost-L"), ("cost_w", "wc1 and wc2 cost-W"), ("m_l", "ml1 m-L"), ("m_w", "wm1 m-W")):
        rows[key], digest = read_rows(paths[key], allowed, what)
        inputs.append(f"% input: {what} windows.jsonl sha256 {digest}\n")
    mc = AM.Macros()
    cost = cost_part(mc, rows["cost_l"] + rows["cost_w"])
    m1 = m1_part(mc, [r for r in rows["m_l"] + rows["m_w"] if r.get("cell", "").startswith("M1.")])
    summary_macros(mc)
    clash = set(mc.names) & other_names()
    if clash:
        raise ValueError(f"names another macro file holds: {sorted(clash)}")
    return {OUT: HEAD + "".join(inputs) + mc.text(),
            TABLES / "ops-cost.tex": TABLE_HEAD + "\n".join(cost) + "\n",
            TABLES / "ops-m1.tex": TABLE_HEAD + "\n".join(m1) + "\n"}


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--cost-l", type=Path, required=True, help="pc1's cost-L windows.jsonl")
    ap.add_argument("--cost-w", type=Path, required=True, help="wc1 and wc2's cost-W windows.jsonl")
    ap.add_argument("--m-l", type=Path, required=True, help="ml1's m-L windows.jsonl")
    ap.add_argument("--m-w", type=Path, required=True, help="wm1's m-W windows.jsonl")
    ap.add_argument("--check", action="store_true", help="compare with the committed files, write nothing")
    a = ap.parse_args(argv)
    out = build({"cost_l": a.cost_l, "cost_w": a.cost_w, "m_l": a.m_l, "m_w": a.m_w})
    if a.check:
        stale = [p for p, t in out.items() if not p.exists() or p.read_text(encoding="utf-8") != t]
        for p in stale:
            print("differs:", p.relative_to(ROOT).as_posix())
        return 1 if stale else 0
    TABLES.mkdir(parents=True, exist_ok=True)
    for p, t in out.items():
        with open(p, "w", encoding="utf-8", newline="\n") as f:
            f.write(t)
    print(f"ops: {len(out)} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
