#!/usr/bin/env python3
"""The paper's counts and tables of the results (results/report-macros.tex, results/tables/*.tex).

    python paper/report_macros.py [--check]

The results half of the paper reports, family by family, exactly the outputs' verdicts. Most of its
numbers are analysis/macros.py's (results/macros.tex), the hard cases' are
paper/hardcase_macros.py's and the design constants paper/design_macros.py's. Three kinds of
number are in none of them, and this file writes them, from the committed results files alone:
  - counts over the outputs: per hypothesis, the cells in Holm, those that pass, the losses and the
    cells untested, not run or short of R (results/decisions.csv, results/not-run.json);
  - counts of the cells that summary.json has short of R, from results/not-run.json (the mixed cell
    on io_uring, the SSH C2 cells), and the reruns of the analysis that checked the macros' TeX
    escaping (results/macros-provenance.json);
  - the tables of the results section and its appendix: every cell of each family with its
    interval and verdict, the invalid windows of every family cell per arm with their reasons
    (results/summary.json), section 10's cells, and the competitors' table.
A table cites the macros of results/macros.tex and results/hardcase-macros.tex by name wherever a
value has one, so the paper prints one value in one way; a value that no macro holds (a count of
sessions or windows, a reason) is written from the results file. Nothing is typed in and nothing is
decided: every verdict is the analysis's text, cut before its first parenthesis, and a reason is
the runner's text with its numbers written N, under a fixed label. An unknown reason, a verdict
the table does not know, a macro name the macro files do not hold, or a count that disagrees
between two results files stops the run. It lives in paper/, as design_macros.py does, because
analysis/ stays as at ANALYSIS_COMMIT.

--check writes nothing and exits 1 if a committed output differs from what this file writes.
"""

from __future__ import annotations

import argparse
import csv
import json
import re
import sys
from collections import Counter
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
RESULTS = ROOT / "results"
sys.path.insert(0, str(ROOT / "analysis"))

import cells as AC  # noqa: E402  analysis/cells.py, read only
import macros as AM  # noqa: E402  analysis/macros.py, read only

DECISIONS = RESULTS / "decisions.csv"
SUMMARY = RESULTS / "summary.json"
NOT_RUN = RESULTS / "not-run.json"
PROVENANCE = RESULTS / "macros-provenance.json"
MACROS = RESULTS / "macros.tex"
HARDCASE = RESULTS / "hardcase-macros.tex"
DESIGN = RESULTS / "design-macros.tex"
OUT = RESULTS / "report-macros.tex"
TABLES = RESULTS / "tables"

HEAD = ("% Generated by paper/report_macros.py from results/decisions.csv, results/summary.json,\n"
        "% results/not-run.json and results/macros-provenance.json. Do not edit. It decides nothing.\n")
TABLE_HEAD = "% Generated by paper/report_macros.py. Do not edit.\n"

HYP_WORDS = {"C1": "COne", "C2": "CTwo", "C3": "CThree", "B3": "BThree", "M1": "MOne", "M2": "MTwo", "M3": "MThree"}
PROTO = {"http1": "HTTP/1.1", "h2c": "h2c", "tls": "TLS", "mqtt": "MQTT", "ssh": "SSH", "tls-stub": "TLS (SNI)"}
SYSTEM = {"nginx": "nginx", "haproxy": "HAProxy", "envoy": "Envoy", "caddy-l4": "caddy-l4", "sslh-ev": "sslh-ev",
          "netty": "Netty", "jetty": "Jetty", "cmux": "cmux", "hyper-util": "hyper-util"}
CASE = {"silent": "silent", "partial-hello": "partial ClientHello"}

# The runners' invalid reasons, numbers written N, and the label a table prints for each. A reason
# that is not here stops the run, so no reason is printed under a label that does not fit it.
REASONS = {
    "TIME-WAIT count N at sample N, N at the baseline": "TIME-WAIT count at a sample differed from the baseline",
    "not settled: W N then N bytes per pending connection (tolerance N)": "W moved beyond its settling bound",
    "N connects failed": "connects failed",
    "errors N% > N%": "error share above its bound",
    "open loop: N% of the exchanges due completed, below N%": "too few of the exchanges due completed",
    "the job was stopped by a signal during this window": "the job was stopped during the window",
    "probe failed: http1: failed (timeout)": "the probe timed out",
    "opgen failed: no report": "the generator wrote no report",
    "opgen wrote no report (exit N)": "the generator wrote no report",
}


def numbers_as_n(s: str) -> str:
    return re.sub(r"\d+(\.\d+)?", "N", s)


def label(reason: str) -> str:
    key = numbers_as_n(reason)
    for k, v in REASONS.items():
        if key == k or (k.startswith("opgen wrote no report") and key.startswith("opgen wrote no report")):
            return v
    raise ValueError(f"no label for the reason {reason!r}")


def verdict_head(v: str) -> str:
    """The verdict as the analysis wrote it, cut before its first parenthesis; a pass of B3 is
    "shown", whose full wording the caption gives."""
    head = v.split(" (")[0]
    if head.startswith("shown: "):
        head = "shown"
    return AM.tex_text(head).replace("<=", "$\\le$")


# ---------------------------------------------------------------- inputs


def read_decisions() -> list[dict]:
    with open(DECISIONS, encoding="utf-8", newline="") as f:
        return list(csv.DictReader(f))


def read_json(path: Path) -> dict:
    return json.loads(path.read_text(encoding="utf-8"))


def macro_names(path: Path) -> set[str]:
    text = path.read_text(encoding="utf-8")
    return set(re.findall(r"\\newcommand\{\\([A-Za-z]+)\}", text))


def truth(s: str) -> bool:
    if s not in ("True", "False", ""):
        raise ValueError(f"not a truth value: {s!r}")
    return s == "True"


# ---------------------------------------------------------------- counts


def counts(dec: list[dict], summary: dict, not_run: dict, prov: dict) -> AM.Macros:
    mc = AM.Macros()
    fams = summary["families"]
    mc.add("CountDecisionRows", AM.count(len(dec)), "rows of results/decisions.csv")
    for hyp, w in HYP_WORDS.items():
        rows = [r for r in dec if r["hyp"] == hyp]
        holm = [r for r in rows if truth(r["holm"])]
        mc.add(f"CountCells{w}", AM.count(len(rows)), f"{hyp}: cells")
        mc.add(f"CountHolm{w}", AM.count(len(holm)), f"{hyp}: cells in Holm")
        mc.add(f"CountPass{w}", AM.count(sum(truth(r["passes"]) for r in holm)), f"{hyp}: cells that pass")
        mc.add(f"CountFail{w}", AM.count(sum(not truth(r["passes"]) for r in holm)), f"{hyp}: cells in Holm that do not pass")
    # The families' totals must agree with summary.json's.
    for fam, hyps in (("C", ("C1", "C2", "C3")), ("B3", ("B3",)), ("M", ("M1", "M2", "M3"))):
        holm = [r for r in dec if r["hyp"] in hyps and truth(r["holm"])]
        if len(holm) != fams[fam]["m"] or sum(truth(r["passes"]) for r in holm) != fams[fam]["passed"]:
            raise ValueError(f"decisions.csv and summary.json disagree on family {fam}")
    cost = [r for r in dec if r["family"] == "C"]
    mc.add("CountCostOutside", AM.count(sum(r["verdict"].startswith("outside the confirmatory cost family") for r in cost)),
           "cost cells outside the family by a logged decision")
    mc.add("CountCostUnresolved", AM.count(sum(r["verdict"].startswith("not resolved") for r in cost)),
           "cost cells the pilot did not resolve")
    mc.add("CountCostMeasured", AM.count(sum("a measured cost" in r["verdict"] for r in cost)),
           "cost cells whose interval lies wholly outside the margin")
    b3 = [r for r in dec if r["family"] == "B3"]
    mc.add("CountLossBThree", AM.count(sum("loss" in r["verdict"] for r in b3)), "B3 cells with a loss")
    desc = [r for r in b3 if not truth(r["holm"])]
    mc.add("CountDescBThree", AM.count(len(desc)), "B3's descriptive cells")
    mc.add("CountDescShortBThree", AM.count(sum(int(r["valid_sessions"]) < int(r["R"]) for r in desc)),
           "B3's descriptive cells short of R")
    m = [r for r in dec if r["family"] == "M"]
    mc.add("CountUntestedM", AM.count(sum(not truth(r["tested"]) for r in m)), "M cells untested (no valid session)")
    statuses = Counter(c["status"] for c in not_run["cells"])
    mc.add("CountNotRunList", AM.count(len(not_run["cells"])), "cells results/not-run.json lists")
    mc.add("CountNotRunNotRun", AM.count(statuses["not run"]), "of them, not run")
    mc.add("CountNotRunShort", AM.count(statuses["ran, short of R"]), "of them, ran and short of R")
    if sum(statuses.values()) != len(not_run["cells"]):
        raise ValueError("not-run.json: a status this file does not know")
    sec = [c for c in not_run["cells"] if c["cell"].startswith("S.")]
    mc.add("CountSecShortNone", AM.count(sum(c["status"] == "ran, short of R" and c["valid_sessions"] == 0 for c in sec)),
           "section 10 cells that ran and have no valid session")
    mc.add("CountSecNotRun", AM.count(sum(c["status"] == "not run" for c in sec)), "section 10 cells not run")
    mc.add("CountSecSslh", AM.count(sum("sslh-ev" in c["cell"] for c in sec)), "section 10 cells of sslh-ev short of R")
    by_id = {c["cell"]: c for c in not_run["cells"]}
    mixed = by_id["S.mixed.C1.L.io_uring"]
    reasons = mixed["rows"]["invalid_reasons_numbers_as_N"]
    mc.add("CountMixedIouringSessions", AM.count(mixed["rows"]["sessions"]), "the mixed cell on io_uring: sessions run")
    mc.add("CountMixedIouringWindows", AM.count(mixed["rows"]["windows"]), "windows")
    mc.add("CountMixedIouringValid", AM.count(mixed["rows"]["valid_windows"]), "valid windows")
    mc.add("CountMixedIouringProbe", AM.count(reasons["probe failed: http1: failed (timeout)"]), "windows whose probe timed out")
    mc.add("CountMixedIouringErrors", AM.count(reasons["errors N% > N%"]), "windows with the error share above its bound")
    ssh = [c for c in sec if c["cell"].startswith("S.ssh.C2.")]
    if len({c["rows"]["windows"] for c in ssh}) != 1 or any(c["rows"]["valid_windows"] for c in ssh):
        raise ValueError("the SSH C2 cells differ in their windows")
    mc.add("CountSshCtwoCells", AM.count(len(ssh)), "section 10's SSH C2 cells")
    mc.add("CountSshCtwoWindows", AM.count(ssh[0]["rows"]["windows"]), "windows of each, none valid")
    lw = prov["hosts"]["L"]["against_W"]
    mc.add("CountEscapedLines", AM.count(len(prov["macros_tex"]["held_back"]["lines_that_differ"])),
           "lines of macros.tex that the escaping changed")
    mc.add("RerunDecisionsMaxRel", AM.scientific(lw["decisions_csv"]["max_rel"]),
           "L against W: decisions.csv's largest relative difference (BCa p-values)")
    mc.add("RerunSummaryMaxAbs", AM.scientific(lw["summary_json_other_fields"]["max_abs"]),
           "L against W: summary.json's largest absolute difference of a float")
    mc.add("RerunPythonL", prov["hosts"]["L"]["runtime"]["python"], "Python of L's rerun")
    if lw["decisions_csv"]["nonfloat_diffs"] or lw["summary_json_other_fields"]["nonfloat_diffs"] or not lw["macros_tex_identical"]:
        raise ValueError("L's rerun differs from W's in more than floats")
    return mc


# ---------------------------------------------------------------- tables


def cell_text(cell_id: str) -> str:
    """C1.L.epoll.http1 -> C1 & L, epoll & HTTP/1.1, for a family's table."""
    p = cell_id.split(".")
    return f"{p[0]} & {p[1]}, {AM.tex_text(p[2])} & {PROTO[p[3]]}"


def interval(w: str, names: set[str], low: str = "Low", high: str = "High") -> str:
    a, b = f"{w}{low}", f"{w}{high}"
    if a in names and b in names:
        return f"[\\{a}, \\{b}]"
    return "none"


def value(name: str, names: set[str]) -> str:
    return f"\\{name}" if name in names else "none"


def math(v: str) -> str:
    """A value that may be negative, in math mode, so that its sign prints as a minus."""
    return v if v == "none" else f"${v}$"


def math_interval(w: str, names: set[str]) -> str:
    a, b = f"{w}Low", f"{w}High"
    if a in names and b in names:
        return f"[$\\{a}$, $\\{b}$]"
    return "none"


def require(name: str, names: set[str]) -> str:
    if name not in names:
        raise ValueError(f"no macro {name}")
    return f"\\{name}"


def cost_table(dec: list[dict], names: set[str]) -> str:
    rows = []
    for r in (r for r in dec if r["family"] == "C"):
        w = AM.word(r["cell"])
        rows.append(f"{cell_text(r['cell'])} & {require(w + 'Valid', names)} & {value(w + 'Median', names)} & "
                    f"{interval(w, names)} & {interval(w, names, 'HolmLow', 'HolmHigh')} & {verdict_head(r['verdict'])} \\\\")
    return TABLE_HEAD + "\n".join(rows) + "\n"


def b3_table(dec: list[dict], names: set[str]) -> str:
    rows = []
    for r in (r for r in dec if r["family"] == "B3"):
        _, case, system, backend = r["cell"].split(".")
        w = AM.word(r["cell"])
        rows.append(f"{CASE[case]} & {SYSTEM[system]} & {AM.tex_text(backend)} & {require(w + 'Valid', names)} & "
                    f"{value(w + 'Median', names)} & {interval(w, names)} & {interval(w, names, 'HolmLow', 'HolmHigh')} & "
                    f"{value(w + 'SignX', names)} & {math(value(w + 'DMedian', names))} & "
                    f"{math_interval(w + 'D', names)} & {verdict_head(r['verdict'])} \\\\")
    return TABLE_HEAD + "\n".join(rows) + "\n"


PARTS = ("W", "U", "Kq", "KsNet", "SkbGrowth", "SharedGrowth", "F")


def b3_parts_table(dec: list[dict], names: set[str], role: str) -> str:
    """The parts of one arm's footprint in every B3 cell: role is "Competitor" or "Server"."""
    rows = []
    for r in (r for r in dec if r["family"] == "B3"):
        _, case, system, backend = r["cell"].split(".")
        w = AM.word(r["cell"])
        if w + role + "W" not in names:
            continue
        parts = " & ".join(math(value(w + role + k, names)) for k in PARTS)
        rows.append(f"{CASE[case]} & {SYSTEM[system]} & {AM.tex_text(backend)} & {parts} \\\\")
    return TABLE_HEAD + "\n".join(rows) + "\n"


def mech_table(dec: list[dict], names: set[str]) -> str:
    rows = []
    for r in (r for r in dec if r["family"] == "M"):
        p = r["cell"].split(".")
        what = f"{AM.tex_text(p[2])}, {PROTO[p[3]]}" + (f", {SYSTEM[p[4]]}" if len(p) > 4 else "")
        w = AM.word(r["cell"])
        rows.append(f"{p[0]} & {p[1]} & {what} & {require(w + 'Valid', names)} & {value(w + 'Median', names)} & "
                    f"{interval(w, names)} & {verdict_head(r['verdict'])} \\\\")
    return TABLE_HEAD + "\n".join(rows) + "\n"


def invalid_table(summary: dict) -> str:
    rows = []
    for fam in ("C", "B3", "M"):
        for x in summary["families"][fam]["cells"]:
            for arm, ws in sorted(x["invalid_windows"].items()):
                labels = Counter(lab for w in ws for lab in {label(reason) for reason in w["reasons"]})
                text = "; ".join(f"{k} ({v})" for k, v in sorted(labels.items(), key=lambda kv: (-kv[1], kv[0])))
                rows.append(f"{AM.tex_text(x['cell'])} & {AM.tex_text(arm)} & {len(ws)} & {text} \\\\")
    return TABLE_HEAD + "\n".join(rows) + "\n"


ROLE = {"one-port": "one-port", "dedicated": "dedicated", "reuseport": "group", "shared": "shared",
        "server": "server", "proxy": "proxy", "variant": "form", "default": "default", "other": "other",
        "inproc": "in-process", "relay": "relay"}
METRIC = {"conn_per_s": "conn./s", "req_per_s": "req./s", "ttfb_median_us": "median TTFB", "W": "W",
          "cpu": "CPU per conn.", None: "conn./s"}
VARIANT = {"resumption": "TLS, resumption", "alpn-h2": "TLS, ALPN h2", "two-cores": "two server cores",
           "reuseport": "SO\\_REUSEPORT group", "acceptex-buffer": "AcceptEx with a buffer",
           "receive-form": "posted receive"}


def secondary_rows() -> list[tuple[str, str, str, str, str, str]]:
    """(bullet, cell id, metric, what, where, ratio and metric) for every interval of section 10 but
    WL4's and the analysis clustered by job, in the analysis's order (analysis/cells.py)."""
    sec = {c.id: c for c in AC.secondary_cells()}
    fam = AC.all_family_cells()
    out = []
    for d in AC.secondary_draws():
        if d.bullet in ("wl4", "by-job"):
            continue
        if d.source in sec:
            c = sec[d.source]
            p = c.id.split(".")
            if c.bullet == "ssh":
                what, metric = f"SSH, {p[2]}", AC.HYP_METRIC[p[2]]
            elif c.bullet == "mixed":
                what, metric = "mixed protocols, C1", c.metric
            elif c.bullet in ("tls-variants", "two-cores", "iocp-forms"):
                what, metric = VARIANT[p[-1]], c.metric
            elif c.bullet == "relay-io_uring":
                what, metric = f"relay, {PROTO[p[4]]}, {SYSTEM[p[5]]}", c.metric
            elif c.bullet == "m-ttfb-cpu":
                m = fam[c.key[0]]
                what = f"{m.hyp} TTFB, {PROTO[m.proto]}" + (f", {SYSTEM[m.system]}" if m.system else "")
                metric = c.metric
            elif c.bullet == "b3-other-mode":
                what, metric = f"B3 other mode, {CASE[p[3]]}", c.metric
            else:
                raise ValueError(f"no row text for bullet {c.bullet}")
            num, den, host, backend = c.num, c.den, c.host, c.backend
        else:
            m = fam[d.source]
            what = f"{m.hyp} CPU, {PROTO[m.proto]}" + (f", {SYSTEM[m.system]}" if m.system else "")
            num, den, host, backend, metric = m.num, m.den, m.host, m.backend, "cpu"
        ratio = f"{ROLE[num]} / {ROLE[den]}, {METRIC[metric]}"
        out.append((d.bullet, d.source, d.metric, what, f"{host}, {AM.tex_text(backend)}", ratio))
    return out


MECH_BULLETS = ("m-ttfb-cpu", "b3-other-mode")


def secondary_tables(summary: dict, not_run: dict, names: set[str]) -> tuple[str, str]:
    """Section 10's cells with sessions of their own, and every M cell's CPU, in the analysis's
    order: the cost-side bullets in one table, the mechanism and B3 bullets in the other."""
    entries = {(e["bullet"], e["cell"], e["metric"]): e for e in summary["secondary"]}
    nr = {c["cell"]: c for c in not_run["cells"]}
    rows: list[tuple[str, str]] = []
    for bullet, cell, metric, what, where, ratio in secondary_rows():
        e = entries[(bullet, cell, metric)]
        w = "Sec" + AM.word(bullet) + AM.word(cell) + AM.word(metric)
        if e.get("interval") is not None:
            shown = f"{require(w + 'Median', names)} & [{require(w + 'Low', names)}, {require(w + 'High', names)}]"
        else:
            c = nr.get(cell)
            if c is None:
                raise ValueError(f"{cell}: no interval and not in not-run.json")
            shown = "\\multicolumn{2}{l}{" + ("not run" if c["status"] == "not run" else "no valid session") + "}"
        rows.append((bullet, f"{what} & {where} & {ratio} & {e['valid_sessions']} & {shown} \\\\"))
    if len(rows) != sum(1 for e in summary["secondary"] if e["bullet"] not in ("wl4", "by-job")):
        raise ValueError("section 10's table and summary.json differ in their cells")
    first = [r for b, r in rows if b not in MECH_BULLETS]
    second = [r for b, r in rows if b in MECH_BULLETS]
    return TABLE_HEAD + "\n".join(first) + "\n", TABLE_HEAD + "\n".join(second) + "\n"


def wl4_table(summary: dict, names: set[str]) -> str:
    rows = []
    cells = []
    for e in summary["secondary"]:
        if e["bullet"] == "wl4" and e["cell"] not in cells:
            cells.append(e["cell"])
    for cell in cells:
        vals = []
        for metric in ("cpu", "rss", "rss_peak", "ttfb_p99"):
            w = "SecWLFour" + AM.word(cell) + AM.word(metric)
            vals.append(f"\\{w}Median{{}} [\\{w}Low, \\{w}High]" if w + "Median" in names else "none")
        rows.append(f"{cell_text(cell)} & " + " & ".join(vals) + " \\\\")
    return TABLE_HEAD + "\n".join(rows) + "\n"


def by_job_table(summary: dict, names: set[str]) -> str:
    rows = []
    for e in summary["secondary"]:
        if e["bullet"] != "by-job" or e.get("interval") is None:
            continue
        w = "SecByJob" + AM.word(e["cell"]) + "Value"
        fam_w = AM.word(e["cell"])
        rows.append(f"{cell_text(e['cell'])} & {require(w + 'Median', names)} & [{require(w + 'Low', names)}, "
                    f"{require(w + 'High', names)}] & {interval(fam_w, names)} \\\\")
    return TABLE_HEAD + "\n".join(rows) + "\n"


def competitors_table(hc_names: set[str]) -> str:
    rows = []
    for system in ("nginx", "haproxy", "envoy", "caddy-l4", "sslh-ev", "netty", "jetty", "cmux", "hyper-util"):
        w = "CompCase" + AM.WORDS[system]
        cols = [f"{w}{k}" for k in ("Rows", "RowsAsExpected", "RowsDiffer", "RowsNotObserved", "Variants",
                                     "MatchedVariantsAsExpected", "MatchedVariantsDiffer", "DefaultVariantsAsExpected",
                                     "DefaultVariantsDiffer", "CasesNotCovered")]
        rows.append(f"{SYSTEM[system]} & " + " & ".join(require(c, hc_names) for c in cols) + " \\\\")
    return TABLE_HEAD + "\n".join(rows) + "\n"


# ---------------------------------------------------------------- main


def build() -> dict[Path, str]:
    dec = read_decisions()
    summary, not_run, prov = read_json(SUMMARY), read_json(NOT_RUN), read_json(PROVENANCE)
    names = macro_names(MACROS)
    hc = macro_names(HARDCASE)
    mc = counts(dec, summary, not_run, prov)
    sec = secondary_tables(summary, not_run, names)
    clash = set(mc.names) & (names | hc | macro_names(DESIGN))
    if clash:
        raise ValueError(f"names another macro file holds: {sorted(clash)}")
    return {
        OUT: HEAD + mc.text(),
        TABLES / "cost.tex": cost_table(dec, names),
        TABLES / "b3.tex": b3_table(dec, names),
        TABLES / "b3-parts-competitor.tex": b3_parts_table(dec, names, "Competitor"),
        TABLES / "b3-parts-server.tex": b3_parts_table(dec, names, "Server"),
        TABLES / "mechanism.tex": mech_table(dec, names),
        TABLES / "invalid.tex": invalid_table(summary),
        TABLES / "secondary.tex": sec[0],
        TABLES / "secondary-mech.tex": sec[1],
        TABLES / "wl4.tex": wl4_table(summary, names),
        TABLES / "by-job.tex": by_job_table(summary, names),
        TABLES / "competitors.tex": competitors_table(hc),
    }


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--check", action="store_true", help="compare with the committed files, write nothing")
    a = ap.parse_args(argv)
    out = build()
    if a.check:
        stale = [p for p, t in out.items() if not p.exists() or p.read_text(encoding="utf-8") != t]
        for p in stale:
            print("differs:", p.relative_to(ROOT).as_posix())
        return 1 if stale else 0
    TABLES.mkdir(parents=True, exist_ok=True)
    for p, t in out.items():
        with open(p, "w", encoding="utf-8", newline="\n") as f:
            f.write(t)
    print(f"report: {len(out)} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
