#!/usr/bin/env python3
"""Section 10's untimed rows of lab job st1 (results/trace-macros.tex and three table bodies).

    python paper/trace_macros.py --trace TRACE.jsonl --calls CALLS.jsonl --clearance CLEARANCE.json [--check]

The revision log's entry "Section 10's four descriptive outputs not yet reported, and their untimed
windows on the frozen build (a reading)", item 5, has st1 run bench/run/systrace.py as frozen on L's
measured build, after the freeze guard (a wrapper calls it and writes the clearance). This file
reads st1's rows and writes:
  (d) the check of the server's system-call counters, one untimed window per cost cell of L in each
      mode: per row, how many of its checks agree with perf stat's count of the same calls' entry
      tracepoints (section 10's check, `stat_agrees`) and with perf trace -s (the cross-check,
      `agrees` of each check), and perf trace's largest shortfall against perf stat
      (`trace_shortfall_max_share`); results/tables/counter-check.tex;
  (c) the proxies' system calls per connection from perf trace -s (every call, over the connections
      the stub accepted), and for the calls the server's checks name, perf trace's and perf stat's
      counts per connection and perf trace's shortfall; the server's relay beside them;
      results/tables/syscalls.tex;
  item 4 (iii) the relay's operations and copies per relayed connection (its counters over its life
      divided by `relayed`), replay and peek on epoll and io_uring; results/tables/ops-relay.tex.
The cost rows' labels name the cost cells: `churn` C1, `keepalive` C2 and `open` C3 (the entry, item
5 (iii)). Nothing timed is read. Every input is checked against the sha256 that design/status.md
names for it, the clearance must name CODE_FREEZE and CHANGE_COMMIT, and the rows must be the 66 the
plan lists, each once. Like the other generators in paper/, this lives outside analysis/.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
RESULTS = ROOT / "results"
STATUS = ROOT / "design" / "status.md"
SUMMARY = RESULTS / "summary.json"
SYSTRACE = ROOT / "bench" / "run" / "systrace.py"
OUT = RESULTS / "trace-macros.tex"
TABLES = RESULTS / "tables"
sys.path.insert(0, str(ROOT / "analysis"))
sys.path.insert(0, str(HERE))

import macros as AM  # noqa: E402  analysis/macros.py, read only: its formatters and store
import ops_macros as OPS  # noqa: E402  rule E's operations, the same sum as WL5's

JOB = "st1"
CODE_FREEZE = "ff2679cc89d23e08a817308c9aeba7901e056fef"
CHANGE_COMMIT = "9cae2deff2b01896bfab25c5af4c610381dc3c1d"
HEAD = ("% Generated by paper/trace_macros.py from lab job st1's untimed rows, named below by their sha256\n"
        "% (design/status.md, st1's follow-up). Do not edit. Descriptive: the revision log's entry of 2026-10-08\n"
        "% on section 10's four outputs, items 4 (iii) and 5.\n")
TABLE_HEAD = "% Generated by paper/trace_macros.py. Do not edit.\n"
HYP_OF = {"churn": "C1", "keepalive": "C2", "open": "C3"}
BACKENDS = ("epoll", "io_uring")
PROTOS = ("http1", "h2c", "tls", "mqtt")
MODES = ("dedicated", "one-port")
MODE_WORD = {"dedicated": "Dedicated", "one-port": "OnePort"}
SYSTEMS = ("nginx", "haproxy", "envoy", "caddy-l4", "sslh-ev")
RELAY = "one-port-relay"
PROXY_PROTOS = ("tls-stub", "http1")
DETECTS = ("replay", "peek")
SYSTEM_TEXT = {"nginx": "nginx", "haproxy": "HAProxy", "envoy": "Envoy", "caddy-l4": "caddy-l4", "sslh-ev": "sslh-ev",
               RELAY: "the server's relay"}
PROTO_TEXT = {"http1": "HTTP/1.1", "h2c": "h2c", "tls": "TLS", "mqtt": "MQTT", "tls-stub": "TLS (SNI)"}
# bench/run/systrace.py's STAT_CALLS: the calls the server's checks name, which perf stat counts.
STAT_CALLS = ("accept4", "accept", "recvfrom", "sendto", "setsockopt", "epoll_ctl", "epoll_pwait2", "epoll_pwait",
              "epoll_wait", "io_uring_enter", "connect", "shutdown", "splice")
RELAY_METRICS = (("Ops", None, 3), ("Copied", "bytes_copied", 1), ("Received", "bytes_received", 1),
                 ("Sent", "bytes_sent", 1), ("Peeked", "bytes_peeked", 1), ("Wakeups", "detection_wakeups", 3))


def sha256_file(path: Path) -> str:
    return hashlib.sha256(Path(path).read_bytes()).hexdigest()


def named(what: str) -> str:
    """The sha256 that design/status.md names for one of st1's files, on a line "st1's `FILE` sha256 HEX"."""
    found = set(re.findall(rf"st1's `{re.escape(what)}` sha256 ([0-9a-f]{{64}})", STATUS.read_text(encoding="utf-8")))
    if len(found) != 1:
        raise ValueError(f"design/status.md names st1's {what} by {len(found)} sha256 values, not one")
    return found.pop()


def read_checked(path: Path, what: str) -> tuple[str, str]:
    digest = sha256_file(path)
    if digest != named(what):
        raise ValueError(f"{path} has sha256 {digest}, not the one design/status.md names for st1's {what}")
    return path.read_text(encoding="utf-8"), digest


def check_clearance(c: dict) -> None:
    """CODE_FREEZE and CHANGE_COMMIT, and oneport and opgen by sha256 among the binaries the gates of
    the confirmatory analysis cover (results/summary.json, gate.covered_binaries)."""
    f = c.get("freeze") or {}
    if f.get("code_freeze") != CODE_FREEZE or f.get("change_commit") != CHANGE_COMMIT:
        raise ValueError(f"the clearance names {f.get('code_freeze')} and {f.get('change_commit')}, not CODE_FREEZE and CHANGE_COMMIT")
    binaries = (c.get("gate") or {}).get("binaries", {})
    if sorted(binaries) != ["oneport", "opgen"]:
        raise ValueError("the clearance does not name the oneport and opgen binaries")
    covered = set(json.loads(SUMMARY.read_text(encoding="utf-8"))["gate"]["covered_binaries"])
    for name, digest in binaries.items():
        if f"{name} {digest}" not in covered:
            raise ValueError(f"the clearance's {name} {digest[:12]} is not a binary the gates cover")


def expected_keys() -> set[tuple]:
    keys = {("cost", w, p, b, m) for w in HYP_OF for b in BACKENDS for p in PROTOS for m in MODES}
    keys |= {("proxy", s, p, "epoll", "replay") for s in SYSTEMS + (RELAY,) for p in PROXY_PROTOS}
    keys |= {("proxy", RELAY, p, b, d) for b in BACKENDS for d in DETECTS for p in PROXY_PROTOS}
    return keys


def row_key(r: dict) -> tuple:
    if r.get("kind") == "cost":
        w, p, b = r["cell"].split(".")
        if r.get("detect") != "replay" or r.get("repeat") != 0:
            raise ValueError(f"{r.get('tag')}: a cost row not in replay, or a repeat")
        return ("cost", w, p, b, r["mode"])
    if r.get("kind") == "proxy":
        relay = r["system"] == RELAY
        return ("proxy", r["system"], r["proto"], r["backend"] if relay else "epoll", r["detect"] if relay else "replay")
    raise ValueError(f"a row of kind {r.get('kind')!r}")


def check_rows(rows: list[dict]) -> dict[tuple, dict]:
    by: dict[tuple, dict] = {}
    for r in rows:
        if r.get("job") != JOB or r.get("untimed") is not True or r.get("development") is not True:
            raise ValueError(f"{r.get('tag')}: a row of job {r.get('job')!r}, or not untimed, or without systrace.py's "
                             "constant development true (the entry, item 5 (ii))")
        k = row_key(r)
        if k in by:
            raise ValueError(f"{r.get('tag')}: a second row of {k}")
        by[k] = r
    want = expected_keys()
    if set(by) != want:
        raise ValueError(f"rows missing: {sorted(want - set(by))[:6]}; rows not planned: {sorted(set(by) - want)[:6]}")
    return by


def load_constants() -> dict[str, float]:
    """The untimed load of bench/run/systrace.py (M4b-1's reading 9), read from the frozen source."""
    text = SYSTRACE.read_text(encoding="utf-8")
    out = {}
    for name in ("TRACE_RATE", "TRACE_WARM_MS", "TRACE_MS", "TRACE_KA_CONNS", "TRACE_KA_MS"):
        m = re.search(rf"^{name} = ([0-9.]+)$", text, re.M)
        if not m:
            raise ValueError(f"{SYSTRACE.name} defines no {name}")
        out[name] = float(m.group(1))
    return out


def load_macros(mc: AM.Macros) -> None:
    c = load_constants()
    mc.add("TraceRate", AM.count(c["TRACE_RATE"]), "the untimed churn's open-loop rate, exchanges per second (systrace.py)")
    mc.add("TraceSeconds", AM.fixed(c["TRACE_MS"] / 1000, 1), "the untimed churn's measured span, s")
    mc.add("TraceWarmSeconds", AM.fixed(c["TRACE_WARM_MS"] / 1000, 1), "the untimed churn's warm-up, s")
    mc.add("TraceKaConns", AM.count(c["TRACE_KA_CONNS"]), "the untimed keep-alive's connections")
    mc.add("TraceKaSeconds", AM.fixed(c["TRACE_KA_MS"] / 1000, 1), "the untimed keep-alive's span, s")


def pct(x: float) -> str:
    return AM.fixed(100 * x, 2)


def counter_check(mc: AM.Macros, by: dict[tuple, dict]) -> list[str]:
    table = []
    totals = {"rows": 0, "rows_stat": 0, "rows_trace": 0, "checks": 0, "stat": 0, "trace": 0, "lost": 0,
              "server_fail": 0, "opgen_fail": 0}
    shortfalls = []
    for w, hyp in HYP_OF.items():
        for b in BACKENDS:
            for p in PROTOS:
                cell = f"{hyp}.L.{b}.{p}"
                word = "Trace" + AM.word(cell)
                cols = []
                for m in MODES:
                    r = by[("cost", w, p, b, m)]
                    checks = r.get("checks") or []
                    n_stat = sum(1 for c in checks if c.get("stat_agrees"))
                    n_trace = sum(1 for c in checks if c.get("agrees"))
                    mw = MODE_WORD[m]
                    mc.add(f"{word}{mw}Checks", AM.count(len(checks)), f"{cell}, {m}: checks of the row")
                    mc.add(f"{word}{mw}StatAgree", AM.count(n_stat), f"{cell}, {m}: checks equal to perf stat's count")
                    mc.add(f"{word}{mw}TraceAgree", AM.count(n_trace), f"{cell}, {m}: checks equal to perf trace's count")
                    cols += [f"\\{word}{mw}StatAgree/\\{word}{mw}Checks", f"\\{word}{mw}TraceAgree/\\{word}{mw}Checks"]
                    totals["rows"] += 1
                    totals["rows_stat"] += r.get("agrees_with_perf_stat") is True
                    totals["rows_trace"] += r.get("agrees") is True
                    totals["checks"] += len(checks)
                    totals["stat"] += n_stat
                    totals["trace"] += n_trace
                    totals["lost"] += int(r.get("perf_lost") or 0)
                    totals["server_fail"] += r.get("server_exit") != 0
                    totals["opgen_fail"] += not (r.get("opgen") or {}).get("ok")
                    if r.get("trace_shortfall_max_share") is not None:
                        shortfalls.append(r["trace_shortfall_max_share"])
                cell_short = max((x for x in (by[("cost", w, p, b, m)].get("trace_shortfall_max_share") for m in MODES)
                                  if x is not None), default=0.0)
                mc.add(f"{word}ShortfallPct", pct(cell_short), f"{cell}: perf trace's largest shortfall, percent of perf stat's count")
                table.append(f"{hyp} & {AM.tex_text(b)} & {PROTO_TEXT[p]} & " + " & ".join(cols) + f" & \\{word}ShortfallPct \\\\")
    for k, name in (("rows", "Rows"), ("rows_stat", "RowsStatAgree"), ("rows_trace", "RowsTraceAgree"), ("checks", "Checks"),
                    ("stat", "ChecksStatAgree"), ("trace", "ChecksTraceAgree"), ("lost", "Lost"),
                    ("server_fail", "ServerFailed"), ("opgen_fail", "OpgenFailed")):
        mc.add(f"TraceCost{name}", AM.count(totals[k]), f"the cost rows: {k}")
    mc.add("TraceCostShortfallMaxPct", pct(max(shortfalls, default=0.0)), "the cost rows: perf trace's largest shortfall, percent")
    mc.add("TraceCostCells", AM.count(totals["rows"] // len(MODES)), "cost cells with an untimed row in each mode")
    return table


def calls_of(r: dict, names: tuple[str, ...] | None, source: str) -> int:
    if source == "trace":
        calls = r.get("perf_calls") or {}
        return sum(int(v.get("calls", 0)) for k, v in calls.items() if names is None or k in names)
    stat = r.get("perf_stat") or {}
    if set(stat) != set(STAT_CALLS):
        raise ValueError(f"{r.get('tag')}: perf stat counted {sorted(stat)}, not systrace.py's STAT_CALLS")
    if any(stat.get(k) is None for k in names):
        raise ValueError(f"{r.get('tag')}: perf stat could not count every checked call")
    return sum(int(stat[k]) for k in names)


def syscalls(mc: AM.Macros, by: dict[tuple, dict]) -> list[str]:
    table = []
    shorts, lost = [], 0
    for s in SYSTEMS + (RELAY,):
        for p in PROXY_PROTOS:
            r = by[("proxy", s, p, "epoll", "replay")]
            word = "TraceSys" + AM.WORDS.get(s, "Relay") + AM.WORDS[p]
            acc = int(r.get("stub_accepted") or 0)
            if acc <= 0:
                raise ValueError(f"{r.get('tag')}: the stub accepted no connection")
            every = calls_of(r, None, "trace")
            ct, cs = calls_of(r, STAT_CALLS, "trace"), calls_of(r, STAT_CALLS, "stat")
            mc.add(f"{word}Conns", AM.count(acc), f"{s} {p}: connections the stub accepted")
            mc.add(f"{word}Calls", AM.fixed(every / acc, 3), f"{s} {p}: system calls per connection, perf trace -s, every call")
            mc.add(f"{word}CheckedTrace", AM.fixed(ct / acc, 3), f"{s} {p}: the checked calls per connection, perf trace -s")
            mc.add(f"{word}CheckedStat", AM.fixed(cs / acc, 3), f"{s} {p}: the checked calls per connection, perf stat")
            shorts.append((cs - ct) / cs if cs else 0.0)
            lost += int(r.get("perf_lost") or 0)
            mc.add(f"{word}ShortfallPct", pct(shorts[-1]), f"{s} {p}: (perf stat - perf trace) / perf stat, checked calls, percent")
            mc.add(f"{word}Lost", AM.count(int(r.get("perf_lost") or 0)), f"{s} {p}: events perf trace reported lost")
            mc.add(f"{word}OpgenOk", "yes" if (r.get("opgen") or {}).get("ok") else "no", f"{s} {p}: opgen ended ok")
            cols = [f"\\{word}{k}" for k in ("Conns", "Calls", "CheckedTrace", "CheckedStat", "ShortfallPct", "OpgenOk")]
            table.append(f"{SYSTEM_TEXT[s]} & {PROTO_TEXT[p]} & " + " & ".join(cols) + " \\\\")
    mc.add("TraceSysShortfallMinPct", pct(min(shorts)), "the twelve rows of the proxies and the relay: smallest shortfall, percent")
    mc.add("TraceSysShortfallMaxPct", pct(max(shorts)), "the twelve rows: largest shortfall, percent")
    mc.add("TraceSysLost", AM.count(lost), "the twelve rows: events perf trace reported lost")
    return table


def relay_ops(mc: AM.Macros, by: dict[tuple, dict]) -> list[str]:
    table = []
    agree = {"rows": 0, "rows_stat": 0, "checks": 0, "stat": 0}
    copied = []
    for b in BACKENDS:
        for p in PROXY_PROTOS:
            for d in DETECTS:
                r = by[("proxy", RELAY, p, b, d)]
                c = r.get("server_counters") or {}
                n = int(c.get("relayed") or 0)
                if n <= 0:
                    raise ValueError(f"{r.get('tag')}: the relay relayed no connection")
                word = "TraceRelay" + AM.WORDS[b] + AM.WORDS[p] + d.capitalize()
                mc.add(f"{word}Relayed", AM.count(n), f"relay {b} {p} {d}: connections relayed")
                per = {k: float(v) / n for k, v in c.items() if isinstance(v, int)}
                per["io_uring_submissions"] = {k: float(v) / n for k, v in (c.get("io_uring_submissions") or {}).items()}
                for mw, key, places in RELAY_METRICS:
                    v = OPS.ops(per) if key is None else per.get(key, 0.0)
                    if mw == "Copied":
                        copied.append(v)
                    mc.add(f"{word}{mw}", AM.fixed(v, places), f"relay {b} {p} {d}: {mw.lower()} per relayed connection")
                cols = [f"\\{word}{k}" for k in ("Relayed",) + tuple(m[0] for m in RELAY_METRICS)]
                table.append(f"{AM.tex_text(b)} & {PROTO_TEXT[p]} & {d} & " + " & ".join(cols) + " \\\\")
                checks = r.get("checks") or []
                agree["rows"] += 1
                agree["rows_stat"] += r.get("agrees_with_perf_stat") is True
                agree["checks"] += len(checks)
                agree["stat"] += sum(1 for x in checks if x.get("stat_agrees"))
    for k, name in (("rows", "Rows"), ("rows_stat", "RowsStatAgree"), ("checks", "Checks"), ("stat", "ChecksStatAgree")):
        mc.add(f"TraceRelay{name}", AM.count(agree[k]), f"the relay's rows (both backends, both modes): {k}")
    mc.add("TraceRelayCopiedMax", AM.fixed(max(copied), 1), "the relay's rows: largest bytes copied in user space per relayed connection")
    return table


def other_names() -> set[str]:
    names: set[str] = set()
    for p in sorted(RESULTS.glob("*macros.tex")):
        if p != OUT:
            names |= set(re.findall(r"\\newcommand\{\\([A-Za-z]+)\}", p.read_text(encoding="utf-8")))
    return names


def build(trace: Path, calls: Path, clearance: Path) -> dict[Path, str]:
    t_text, t_sha = read_checked(trace, "trace.jsonl")
    c_text, c_sha = read_checked(calls, "calls-st1.jsonl")
    k_text, k_sha = read_checked(clearance, "clearance-st1.json")
    check_clearance(json.loads(k_text))
    rows = [json.loads(x) for x in t_text.splitlines() if x.strip()]
    call_rows = [json.loads(x) for x in c_text.splitlines() if x.strip()]
    by = check_rows(rows)
    mc = AM.Macros()
    mc.add("TraceJobCalls", AM.count(len(call_rows)), "st1: systrace.py calls")
    mc.add("TraceJobCallsFailed", AM.count(sum(1 for c in call_rows if c.get("exit") != 0)), "st1: calls with a nonzero exit")
    mc.add("TraceJobRows", AM.count(len(rows)), "st1: rows")
    load_macros(mc)
    check = counter_check(mc, by)
    sysc = syscalls(mc, by)
    relay = relay_ops(mc, by)
    clash = set(mc.names) & other_names()
    if clash:
        raise ValueError(f"names another macro file holds: {sorted(clash)}")
    inputs = "".join(f"% input: st1's {w} sha256 {d}\n" for w, d in
                     (("trace.jsonl", t_sha), ("calls-st1.jsonl", c_sha), ("clearance-st1.json", k_sha)))
    return {OUT: HEAD + inputs + mc.text(),
            TABLES / "counter-check.tex": TABLE_HEAD + "\n".join(check) + "\n",
            TABLES / "syscalls.tex": TABLE_HEAD + "\n".join(sysc) + "\n",
            TABLES / "ops-relay.tex": TABLE_HEAD + "\n".join(relay) + "\n"}


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--trace", type=Path, required=True, help="st1's trace.jsonl")
    ap.add_argument("--calls", type=Path, required=True, help="st1's calls-st1.jsonl")
    ap.add_argument("--clearance", type=Path, required=True, help="st1's clearance-st1.json")
    ap.add_argument("--check", action="store_true", help="compare with the committed files, write nothing")
    a = ap.parse_args(argv)
    out = build(a.trace, a.calls, a.clearance)
    if a.check:
        stale = [p for p, t in out.items() if not p.exists() or p.read_text(encoding="utf-8") != t]
        for p in stale:
            print("differs:", p.relative_to(ROOT).as_posix())
        return 1 if stale else 0
    TABLES.mkdir(parents=True, exist_ok=True)
    for p, t in out.items():
        with open(p, "w", encoding="utf-8", newline="\n") as f:
            f.write(t)
    print(f"trace: {len(out)} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
