#!/usr/bin/env python3
"""Two readings of archived W rows that the paper owes its reader (results/w-evidence-macros.tex).

    python paper/w_evidence_macros.py --pilot-w PILOT_W_WINDOWS.jsonl --m-w M_W_WINDOWS.jsonl \
                                      [--out results/w-evidence-macros.tex] [--check]

1. Why W's churn of h2c and MQTT is outside the cost family. The revision log's entry "The job's
   warm-up and W's runners (M7e), before the code freeze", item 2, says that the paper's evidence
   that these cells are generator-bound comes from the A/A pilot's rows, which hold the server's CPU
   busy share (`server_cores_busy`), the generator CPUs' busy share (`gen_cpus_busy_pct`) and the
   generator process's own share (`cpu_shares.generator_process`). This file reads W's pilot rows
   (named by their sha256 in the pilot entry, item 4) and writes, for each C1 cell on W, the median
   of each share over the cell's valid windows. Both arms of the pilot run dedicated mode, so no
   one-port value is read.
2. How often M1's peek on IOCP switched to replay. Frozen section 5.3 says that on IOCP the peek mode
   includes the switch to replay and that the counters report how often. This file reads W's M1 rows
   (job wm1, named by their sha256 in results/summary.json's inputs) and writes, per M1 cell on W,
   the switches (`server_counters.peek_to_replay`) and the connections accepted in the valid windows
   of each detection mode.

Nothing is decided here and nothing is compared: the values are descriptive, and every input is
checked against the sha256 the repository names for it before it is read. It lives in paper/, as
design_macros.py does, because analysis/ stays as at ANALYSIS_COMMIT.
"""

from __future__ import annotations

import argparse
import hashlib
import json
import re
import statistics
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
ROOT = HERE.parent
HYP = ROOT / "hypotheses.md"
SUMMARY = ROOT / "results" / "summary.json"
OUT = ROOT / "results" / "w-evidence-macros.tex"
sys.path.insert(0, str(ROOT / "analysis"))

import macros as AM  # noqa: E402  analysis/macros.py, read only: its formatters

HEAD = ("% Generated by paper/w_evidence_macros.py from W's A/A pilot rows and W's M1 rows, each named by\n"
        "% its sha256 (the pilot entry, item 4; results/summary.json's inputs). Do not edit. Descriptive.\n")
PILOT_CELLS = {"C1.W.IOCP.http1": "Http", "C1.W.IOCP.tls": "Tls", "C1.W.IOCP.h2c": "Htwoc", "C1.W.IOCP.mqtt": "Mqtt"}
M_CELLS = {"M1.W.IOCP.http1": "Http", "M1.W.IOCP.h2c": "Htwoc"}


def sha256(path: Path) -> str:
    h = hashlib.sha256()
    with open(path, "rb") as f:
        for chunk in iter(lambda: f.read(1 << 20), b""):
            h.update(chunk)
    return h.hexdigest()


def pilot_w_sha256() -> str:
    """W's pilot rows, as the pilot entry, item 4, names them."""
    text = " ".join(HYP.read_text(encoding="utf-8").split())
    found = re.findall(r"W's `windows\.jsonl` ([0-9a-f]{64}) and `parts\.jsonl`", text)
    if len(found) != 1:
        raise ValueError(f"hypotheses.md names W's pilot rows {len(found)} times, not once")
    return found[0]


def summary_sha256s() -> set[str]:
    s = json.loads(SUMMARY.read_text(encoding="utf-8"))
    return {i["sha256"] for i in s["inputs"]}


def read_rows(path: Path, allowed: set[str], what: str) -> list[dict]:
    digest = sha256(path)
    if digest not in allowed:
        raise ValueError(f"{what}: {path} has sha256 {digest}, which the repository does not name")
    return [json.loads(line) for line in path.read_text(encoding="utf-8").splitlines() if line.strip()]


def pct(x: float) -> str:
    return AM.fixed(100 * x, 1)


def pilot_macros(mc: AM.Macros, rows: list[dict]) -> None:
    counts = set()
    for cell, w in PILOT_CELLS.items():
        valid = [r for r in rows if r.get("cell") == cell and r.get("valid") is True]
        if not valid or any(r.get("mode") != "dedicated" for r in valid):
            raise ValueError(f"{cell}: no valid pilot window, or a window not in dedicated mode")
        counts.add(len(valid))
        mc.add(f"PilotW{w}ServerBusy", pct(statistics.median(r["server_cores_busy"] for r in valid)),
               f"{cell}: median server CPU busy, percent")
        mc.add(f"PilotW{w}GenCpusBusy", AM.fixed(statistics.median(r["gen_cpus_busy_pct"] for r in valid), 1),
               f"{cell}: median generator CPUs busy, percent")
        mc.add(f"PilotW{w}GenProcess", pct(statistics.median(r["cpu_shares"]["generator_process"] for r in valid)),
               f"{cell}: median generator process share of its CPUs, percent")
    if len(counts) != 1:
        raise ValueError(f"the pilot's C1 cells on W differ in their valid windows: {sorted(counts)}")
    mc.add("PilotWWindows", AM.count(counts.pop()), "valid pilot windows per C1 cell on W")


def switch_macros(mc: AM.Macros, rows: list[dict]) -> None:
    for cell, w in M_CELLS.items():
        for detect, word in (("peek", "Peek"), ("replay", "Replay")):
            valid = [r for r in rows if r.get("cell") == cell and r.get("detect") == detect and r.get("valid") is True]
            if not valid:
                raise ValueError(f"{cell}: no valid window in {detect}")
            mc.add(f"SwitchIocp{w}{word}Windows", AM.count(len(valid)), f"{cell}, {detect}: valid windows")
            mc.add(f"SwitchIocp{w}{word}Accepted", AM.count(sum(r["server_counters"]["accepted"] for r in valid)),
                   f"{cell}, {detect}: connections accepted")
            mc.add(f"SwitchIocp{w}{word}Switches", AM.count(sum(r["server_counters"]["peek_to_replay"] for r in valid)),
                   f"{cell}, {detect}: undecided peeks switched to replay")


def build(pilot_w: Path, m_w: Path) -> str:
    mc = AM.Macros()
    pilot_macros(mc, read_rows(pilot_w, {pilot_w_sha256()}, "W's pilot rows"))
    switch_macros(mc, read_rows(m_w, summary_sha256s(), "W's M1 rows"))
    return HEAD + mc.text()


def main(argv: list[str] | None = None) -> int:
    ap = argparse.ArgumentParser(description=__doc__, formatter_class=argparse.RawDescriptionHelpFormatter)
    ap.add_argument("--pilot-w", type=Path, required=True)
    ap.add_argument("--m-w", type=Path, required=True)
    ap.add_argument("--out", type=Path, default=OUT)
    ap.add_argument("--check", action="store_true", help="compare with the committed file, write nothing")
    a = ap.parse_args(argv)
    text = build(a.pilot_w, a.m_w)
    if a.check:
        same = a.out.exists() and a.out.read_text(encoding="utf-8") == text
        print("same" if same else f"differs: {a.out}")
        return 0 if same else 1
    with open(a.out, "w", encoding="utf-8", newline="\n") as f:
        f.write(text)
    print(f"w evidence: {text.count(chr(10)) - 2} macros to {a.out}")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
